### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by antoine-cherfane** [pi-apps/pi-platform-docs#1]
Hello,

I was trying to use the pi-sdk with the example provided using the following HTML file
```html
<!DOCTYPE html>
<html>
    <head>
        <!-- Pi SDK -->
        <script src="https://sdk.minepi.com/pi-sdk.js"></script>
    </head>
</html>
<script>
    const onOpenPaymentFound = (payment) => {
        console.log("in onOpenPaymentFound");
        console.log(payment);
    }

    const scopes = ["username", "payments"];

    Pi.authenticate(scopes, onOpenPaymentFound).then(function(auth) {
        console.log(`Hello ${auth.user.username}. Your unique ID is ${auth.user.pi_id}`);
    }).catch(function(error) {
        console.error(error);
    });
</script>
```

But I keep getting the following error in my console so I can't do anything with the pi-sdk.

```console
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://app-cdn.minepi.com') does not match the recipient window's origin ('https://vhost.local.com').
```

`https://vhost.local.com` being my local domain but it gives me this error even on localhost and on the domain verified on Pi Developer Portal.

I saw a lot of solutions by using iframe but this will slow down the whole website and it still didn't work in my case.

Is this a problem I can fix from my side or is it something that should be fixed in the sdk?

**Comment by mitjans** [comment]
You have to browser your webapp using Pi Browser

**Comment by antoine-cherfane** [comment]
Deal, thanks!

**Comment by Sten435** [comment]
> Deal, thanks!

Can i contact you on discord i have a question: my discord username is: Stan Persoons#1772

**Comment by aurelienshz** [comment]
See also #11.
