### ISSUE TITLE
/me Endpoint Showing 401 http code

### ISSUE THREAD

**Issue by Heftybrains** [pi-apps/pi-platform-docs#127]
Me Endpoint Showing 401 http code why trying to access it through my PHP backend. Below is an excerpt of my code. 

`<?php 
 $token = "eam0JsPzcZDvGq24tal3VBUsqgzVE-GWYjU";
	//url
	$url = 'https://api.minepi.com/v2/me';
	$ch = curl_init($url);
	# Setting our options 
	$headers = array( "Authorization:Bearer  $token", ); 
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	//curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 	
	# Get the response 
	$result = curl_exec($ch); 
	$error = curl_error($ch);
	$httpcode=curl_getinfo($ch, CURLINFO_HTTP_CODE);
	curl_close($ch); 
	$puser = json_decode($result, true);
	echo $puser;
	echo $result;
	echo "Test Work";
	echo $httpcode;
	echo $error;
?>`
Page Result 
Test Work
401

**Comment by 0205miss** [comment]
The token has a Expired Time. 
If you are using an old token, please update it.

**Comment by Heftybrains** [comment]
Updated it still d same thing

**Comment by Roy8290** [comment]
Sir
My mobail was loss I am pi user
And minging long time. Please help  attech my new mobail number

**Comment by Heftybrains** [comment]
It's working now, replaced my code with the following $token ="Bearer ".$_POST['token'];
$headers = array( "Authorization: ".$token, );
