### ISSUE TITLE
Online job

### ISSUE THREAD

**Issue by Mahealom** [pi-apps/pi-platform-docs#128]
Good projectThe project is implemented professionally and has a clear development plan. Made by a very professional and experienced team. Without doubt, this is one of the best project

**Comment by Mahealom** [comment]
Nice project

**Comment by Auaman11** [comment]
> Good projectThe project is implemented professionally and has a clear development plan. Made by a very professional and experienced team. Without doubt, this is one of the best project

Thanks Sir

**Comment by trieuphuvn2022** [comment]
Nhân Vật số 8 ( Vanga ) - Hoà Bình 1000 năm ( Pi blockchain )
Love Pi - Love All
Cảm ơn tất cả - Cảm ơn vũ trụ 
🅿ℹ❤⚡💎
