### ISSUE TITLE
Pi KYC

### ISSUE THREAD

**Issue by Kashiflohaar** [pi-apps/pi-platform-docs#129]
In my country pakistan much peoples waiting for KYC i humble request to you all that tell the right way for my country peoples that how they
do own KYC and how much time required for it

**Comment by 51t1n74k** [comment]
👍

**Comment by Kashiflohaar** [comment]
Buddy your account has KYC'd?

**Comment by Passionate4145** [comment]
What's my next move

**Comment by Finley269** [comment]
I still waiting for them to send me to kyc!

**Comment by Ham302211** [comment]
Not yet kyc

**Comment by Tinye420** [comment]
I wish I was KYC’d . I feel like all the cool kids got KYC’d and I’m never going to have a girlfriend .. I mean im never gonna KYC

**Comment by Kashiflohaar** [comment]
Sure

**Comment by Mrico30** [comment]
I want to ask, how to KYC?
I never have the invitation for KYC, anyone can help me for KYC please.

My user name : @Mrico30
Thankyou very much.

**Comment by Ahmedjamal66** [comment]
I want to trust

**Comment by hklee93** [comment]
Hi everyone. This is not a right place to ask for KYC. Keep an eye on the in-app announcement and if you need support, please reach out to our support portal at https://minepi.com/faq

**Comment by asaocugdc** [comment]
toi su dung dien thoai he dieu hanh androi 5 toi vao mot so ung dung tren Pi browser "pi blokchain,pi developer protal,pi hackathon va pi kyc"man hinh cu bi trang xoa,nhu vay co sao khong?
