### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Sadisuumar77** [pi-apps/pi-platform-docs#13]

**Comment by Sten435** [comment]
Only place issues with meaning here! 
Don't spam please.

Greetings.

**Comment by EstherSarianSow** [comment]
I don't understand guys

**Comment by dannybutterfield1880** [comment]
This github repository is for people who want to build their own pi network app and integrate the software development kit. For any general questions about Pi please visit the chat rooms in the pi network app or read the FAQs

**Comment by FazalAmin1986** [comment]
Thanks

**Comment by Sten435** [comment]
@Sadisuumar77 please close this issue.

Greetings
