### ISSUE TITLE
Payment to the user

### ISSUE THREAD

**Issue by Deadlolo** [pi-apps/pi-platform-docs#131]
Hi i'm trying to create a P2E game on Pi network and i wanted to know is there a way to send a payment from my app to the user ?

**Comment by Ham302211** [comment]
I dont know how to pay....and button pay not availabed

**Comment by hklee93** [comment]
@Deadlolo Hi, thanks for reaching out. We do have a plan to support App-To-User payment will be supported shortly. Once it's deployed, we will have the official doc updated. Feel free to open again if we don't update it soon 😉
