### ISSUE TITLE
How to get userinfo by Api?

### ISSUE THREAD

**Issue by popyelove** [pi-apps/pi-platform-docs#132]
There's only js-sdk that i see. but how to get user info by api on the backend?

**Comment by Degeneral09** [comment]
#132

**Comment by hklee93** [comment]
You need to authenticate the user using the sdk to access user's info because it requires user's consent.

**Comment by popyelove** [comment]
thanks,i already fix that problem. i want to know when will the sdk support to transfer pi coins to users. this is really impormt feature.
