### ISSUE TITLE
the payment pi test server went wrong?

### ISSUE THREAD

**Issue by popyelove** [pi-apps/pi-platform-docs#135]
when i approve the payment on my backend server,i got this error logs from pi server.
022/02/17 01:55:32.775 [I]  PiOrderApprove-----> map[pid:KcDVMBCvAdtM38WrQKnPPQcU4VPx]
2022/02/17 01:55:32.905 [I]  piorder2----> <!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  .rails-default-error-page {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  .rails-default-error-page div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  .rails-default-error-page div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);

**Comment by chrisspradling1980** [comment]
I'm not a specialist when it comes to blockchain however I am familiar with the physical science side and how it operates outside of healthcare. Being that the only diplomatic person which could stand for the physical science perspective to blend healthcare professionally and privately has passed away unfortunately. He was remembered for his litigation and his presentation with litigation and class then he was also noted academically by the aspect of presentation per class and how the class represented the programming language which would liaison between sociological pseudo pharmaceutical oncology and allowing pie to be a physical environment that could be a private entity organization and as far as I'm concerned answer the best of my knowledge currently, there is no known representative on the face of this planet that can allow physical science technology to be privatized inside the United States of America or anywhere in the world.

**Comment by chrisspradling1980** [comment]
May I please make a correction, Dr Ben Carson was recently housing in urban development in the United States government the director and is also a neuroscientist. Dr Ben Carson is the only person that can put pi into a privatization Enterprise.

**Comment by hklee93** [comment]
I believe it was a temporary issue. Please open a new issue if you face another payment issue.
