### ISSUE TITLE
"Payment data is invalid. Please reach out to developer."

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#14]
I'm having this issue. When I try to make a payment to the app, I have this messsage:

Title of the window: Error!
Message: "Payment data is invalid. Please reach out to developer."

I'm using these docs: https://github.com/pi-apps/pi-platform-docs

This is the code I'm using:
Example app (Pi Browser): https://piapp-example.latin-chain.com/
Code: https://github.com/rockcesar/PiNetworkDevelopments/blob/master/piapp-example/index.html

I have other code with the same issue:
Pidoku app (Pi Browser): https://sudoku.latin-chain.com/
Code: https://github.com/rockcesar/PiNetworkDevelopments/blob/master/sudoku/pidoku/functions.js

Snake app (Pi Browser): https://snake.latin-chain.com/
Code: https://github.com/rockcesar/PiNetworkDevelopments/blob/master/snake/responsive-snake/example/js/functions.js

Image of error:
![pi_dev](https://user-images.githubusercontent.com/5984401/123863846-11612400-d8f8-11eb-9869-24ee138d7da8.jpeg)

**Comment by Sten435** [comment]
I have a simmular error, when i exec the payment function i dont get a response and the server just gives me a timeout after 6000ms

**Comment by Sten435** [comment]
https://user-images.githubusercontent.com/44066744/123875336-c831c400-d939-11eb-9bd7-f826adf7501e.mp4

**Comment by rockcesar** [comment]
> I have a simmular error, when i exec the payment function i dont get a response and the server just gives me a timeout after 6000ms

Share the specific code where you are defining the Pi.createPayment, to see if we can help.

**Comment by EstherSarianSow** [comment]
Can someone teach me about this app and how to pay

**Comment by aszasz1234** [comment]
Your input data is wrong for creating payment

**Comment by aszasz1234** [comment]
> I have a simmular error, when i exec the payment function i dont get a response and the server just gives me a timeout after 6000ms

You need to post message to Π server to check the create payment. See the platform sdk to know how it post

**Comment by Ibdende** [comment]
Can someone teach me about this app and how to pay

**Comment by SuperHax** [comment]
> > I have a simmular error, when i exec the payment function i dont get a response and the server just gives me a timeout after 6000ms
> 
> Share the specific code where you are defining the Pi.createPayment, to see if we can help.

i got the same problem,how to fix this

**Comment by aurelienshz** [comment]
Hi @rockcesar ! Thanks for the detailed issue, and thanks for providing code examples. It makes it so much easier to help you.

From the code example you provided, it looks like you're passing an empty object as the payment's metadata [here](https://github.com/rockcesar/PiNetworkDevelopments/blob/master/PiDevelopment_test1/public/index.html#L63). That's why you're getting a validation error. Metadata is mandatory, because it enables the developer to know what the user was paying for, even if they somehow failed to record the payment on their side (similar to the memo, but the memo is more of a user-facing description, whereas the metadata can be processed programmatically).

Since it looks like your app is simply receiving donation, you could put something to record this fact in the metadata - e.g `{paymentType: "donation"}`. In the future

This is all up to your own internal business logic, but you just need to pass _something_ in the payment's metadata object.

I do agree that this error was very obscure, and that it would have been much better if you had received a message like "metadata can't be empty". I've created a new issue with our internal issue tracker on the SDK side to record the fact that we should return a clearer error message.

**Comment by rockcesar** [comment]
Hello, @aurelienshz , I changed the code as you said, and it changed its behavior, now I'm having the same issue than @Sten435 

https://github.com/pi-apps/pi-platform-docs/issues/14#issuecomment-870958269

**Comment by rockcesar** [comment]
Thank by detailed answer, by the way.

**Comment by rockcesar** [comment]
I updated the code in github, you can check the current code.

https://github.com/pi-apps/pi-platform-docs/issues/14#issue-933049175

**Comment by aszasz1234** [comment]
> I updated the code in github, you can check the current code.
> 
> 
> 
> https://github.com/pi-apps/pi-platform-docs/issues/14#issue-933049175

You should do the ServerApproval by using platform SDK

**Comment by rockcesar** [comment]
> > I updated the code in github, you can check the current code.
> > [#14 (comment)](https://github.com/pi-apps/pi-platform-docs/issues/14#issue-933049175)
> 
> You should do the ServerApproval by using platform SDK

@aszasz1234 Do you have an example?.

**Comment by rockcesar** [comment]
Done, it is working, I sent the ServerApproval and ServerComplete.

@SuperHax @Sten435 @aurelienshz @aszasz1234

Check an example here:

Example app (Pi Browser): https://piapp-example.web.app/
Code: https://github.com/rockcesar/PiNetworkDevelopments/blob/master/PiDevelopment_test1/public/index.html

**Comment by dannybutterfield1880** [comment]
Wait... You have merged the server side and client code? The approve and complete calls should not come from the client side as it includes the apiKey. This logic should be split. I am going to release a detailed guide later using firebase functions, node, express and axios for the requests

**Comment by dannybutterfield1880** [comment]
Also you have published your apiKey

**Comment by rockcesar** [comment]
> Wait... You have merged the server side and client code? The approve and complete calls should not come from the client side as it includes the apiKey. This logic should be split. I am going to release a detailed guide later also using firebase functions but I have made it isomorphic with node, express and axios for the requests on the server side and react and axios on the client side

First, my code is OpenSource, everything in the code I publish it.

The API Key is related to the URL and Pi User, my API Key is useless for another Server.

And I won't use Backend by now, only Frontend.

**Comment by dannybutterfield1880** [comment]
@rockcesar sorry I'll explain if you send the API call from the client then the API key you are sending is exposed in the client network requests that why that request must be sent from the server and not the the browser

**Comment by rockcesar** [comment]
> @rockcesar sorry I'll explain if you send the API call from the client then the API key you are sending is exposed in the client network requests that why that request must be sent from the server and not the the browser

It will be sent through HTTPS. Not exposed.

**Comment by dannybutterfield1880** [comment]
@rockcesar that's not how it works. 

![IMG_20210701_190857.jpg](https://user-images.githubusercontent.com/62266392/124170959-db5ea400-da9f-11eb-94d5-034d4c16dc0f.jpg)

**Comment by rockcesar** [comment]
> @rockcesar that's not how it works.
> 
> ![IMG_20210701_190857.jpg](https://user-images.githubusercontent.com/62266392/124170959-db5ea400-da9f-11eb-94d5-034d4c16dc0f.jpg)

Is it working or not?. HTTPS exists or not?

**Comment by dannybutterfield1880** [comment]
@rockcesar what do you mean? Yes it will work but people will easily be able to see your API key if they know how too by inspecting the POST request. Therefore it's not viable. The server side code needs to run off a server and the client side on the client side it can't be combined

**Comment by rockcesar** [comment]
> @rockcesar what do you mean? Yes it will work but people will easily be able to see your API key if they know how too by inspecting the POST request. Therefore it's not viable. The server side code needs to run off a server and the client side on the client side it can't be combined

API Key is related with Server, it's useless for other Servers.

I don't have server side. I'll do it like this.

**Comment by dannybutterfield1880** [comment]
Ok then 😊 you do you my friend I'm only trying to help you in a full stack web developer with 7 years experience with PHP and JavaScript

**Comment by dannybutterfield1880** [comment]
No worries

**Comment by rockcesar** [comment]
> Ok then blush you do you my friend I'm only trying to help you in a full stack web developer with 7 years experience with PHP and JavaScript

Ok, I can help you, I have 12 years of experience in PHP.

**Comment by dannybutterfield1880** [comment]
Nice 👍 isomorphic JavaScript is completely different

**Comment by dannybutterfield1880** [comment]
Ok 👍

**Comment by rockcesar** [comment]
> Nice +1 isomorphic JavaScript is completely different

Yes, I have 12 years of experience in JavaScript, 12 year of experience in JavaScript, 16 years of experience in Java, 18 years in C, 18 years in C++, 8 years of experience in Python.

I can help you.

**Comment by dannybutterfield1880** [comment]
I'm not even trying to argue with you. I was simply trying to help! I suppose yeah your running PHP it is all running server side I understand that.

**Comment by rockcesar** [comment]
> I'm not even trying to argue with you. I was simply trying to help! I suppose yeah your running PHP it is all running server side I understand that.

I'm using JavaScript, nothing else.

**Comment by dannybutterfield1880** [comment]
All I was saying was I thought the logic should be split so I am making a request from my web app to an API I have built running server side. Then on the server side i am calling the approve and complete end points if that makes sense. I'm going to put up a guide later as I am using full stack JavaScript which is different to you anyway

**Comment by dannybutterfield1880** [comment]
Ohh ok

**Comment by rockcesar** [comment]
> All I was saying was I thought the logic should be split so I am making a request from my web app to an API I have built running server side. Then on the server side i am calling the approve and complete end points if that makes sense. I'm going to put up a guide later as I am using full stack JavaScript which is different to you anyway

That's your logic, but I'm using JavaScript, nothing else.

**Comment by rockcesar** [comment]
If you don't know how to call it from JavaScript, there is my example. I can help you.

**Comment by dannybutterfield1880** [comment]
This isn't correct though my friend

**Comment by rockcesar** [comment]
> This isn't correct though my friend

Ok, your though is correct, not mine ok. Maybe you are Mod in Pi chat, all speak the same xDDDDD. Keep in Pi chat.

And you welcome by my JavaScript example.

**Comment by dannybutterfield1880** [comment]
I'm currently with my kids. Once they go to bed I'm going write up a guide on how to do the server side part of the payment process

**Comment by rockcesar** [comment]
> I'm currently with my kids. Once they go to bed I'm going write up a guide on how to do the server side part of the payment process

Meanwhile you mod in Pi chat. Fine.

It's decentralized, I do what I want. Thanks.

**Comment by dannybutterfield1880** [comment]
Ok I'm not arguing with you. That's fine but read the documentation first properly

**Comment by rockcesar** [comment]
> Ok I'm not arguing with you. That's fine but read the documentation first properly

First learn how to use JavaScript to teach. I can help you.

**Comment by dannybutterfield1880** [comment]
Lol your just being ridiculous now

**Comment by rockcesar** [comment]
> Lol your just being ridiculous now

After you see my example, and learn from it you said something xDD. Perfect, genius.

**Comment by rockcesar** [comment]
Write the guide with my example xDDD. Ok, genius.

**Comment by dannybutterfield1880** [comment]
🙄😂

**Comment by dannybutterfield1880** [comment]
I would rather use the pi platform docs here thanks mate

**Comment by chipmoon27** [comment]
Please guys lets stick to proper decorum here lets stay respectful, and on topic, with that said all aspects of the documentation should be adhered to for safety of the community.

**Comment by Sten435** [comment]
I agree with @chipmoon27 there is no reason to debait on what is the best way to post an http request with an API key.

If you want to do it on the front-end and you know the risks ans are fine with them then why not.

If you want to use it with a server to not expose your API key thats a bit safer but its personal prefferancess.

I and the rest here dont want a debait fight over chat.

Your both realy experianced and have your own thoughts about certain items...

Greetings
Stan P

**Comment by dannybutterfield1880** [comment]
@Sten435 I appreciate people knowing the risk and not caring. That's purely their choice, however the documentation states that the API key definitely should not be used client side. I was just trying to warn him that Core Team will probably not allow that and any developers doing that will be penalised.

**Comment by dannybutterfield1880** [comment]
Also... If something's worth doing and all that

**Comment by Sten435** [comment]
> @Sten435 I appreciate people knowing the risk and not caring. That's purely their choice, however the documentation states that the API key definitely should not be used client side. I was just trying to warn him that Core Team will probably not allow that and any developers doing that will be penalised.

Yea, i agree with you.

I thibk serverside is bether for safety and becuse of the docu.

Greetings
Stan P

**Comment by rockcesar** [comment]
If there is a risk in using in JavaScript because other could use it, it has to be improved in the core, match Key auth with URL and address destination.

Key => URL, Address of developer

If anyone uses it in its own server, the funds will go to the Address of developer or there will be an error. It can be developer, because in develop.pi there is that match. The Key comes from my account, should be related to it.

**Comment by dannybutterfield1880** [comment]
Or just completely hide it in your server side like this [server-side](https://github.com/dannybutterfield1880/fire-pi-base/blob/main/functions/pi-network/services.js)

**Comment by rockcesar** [comment]
Ok, I did the server side.

You can watch an example of PHP here:

https://github.com/rockcesar/PiNetworkDevelopments/blob/master/server1.php

**Comment by dannybutterfield1880** [comment]
@rockcesar that is awesome 👍. Are you able to call the /approve and /complete API endpoints? I'm currently receiving 500 errors from the pi servers.

**Comment by rockcesar** [comment]
@dannybutterfield1880 Yes, I got the same response, because I was sending this in the header. But I solved, in the header of the /approve and /complete call, only send Authorization: Key ...

In /complete, you have to send also the txid in the body.

**Comment by rockcesar** [comment]
I was sending in the header, as the request was json, but it seems, it doesn't needs.

**Comment by dannybutterfield1880** [comment]
@rockcesar @rockcesar I wasn't passing txid to the body 🙄🤦🏼‍♂️ lol sorted now. Nice one 👍

**Comment by rockcesar** [comment]
@dannybutterfield1880 cool!

**Comment by Muhamadhendiabdilah** [comment]
Adakah Apk yang bisa menjadikan pi uang nyat

**Comment by rockcesar** [comment]
> Adakah Apk yang bisa menjadikan pi uang nyat

No.

**Comment by rockcesar** [comment]
Ok, it was solved. I guess it can be closed.
