### ISSUE TITLE
Pi Browser IOS can not save localStorage and cookie in my pi app

### ISSUE THREAD

**Issue by joingreen** [pi-apps/pi-platform-docs#142]
LocalStorage and Cookies do not work for Pi Apps (non-Pi Apps it works).  It removes all when I close the Pi Browser.  But on Android there is no such case. Please help me

**Comment by 0205miss** [comment]
This is because third party cookie will be blocked base on policy

**Comment by WK008HK0** [comment]
Is there a solution to this problem, please let me know, I have this problem too, I need help

**Comment by 0205miss** [comment]
I'm using LocalStorage normal, but cookie can't because of policy on Safari block the third party cookie

**Comment by WK008HK0** [comment]
Hello, I would like to ask how to initiate the payment and how to receive the payment return. I hope I can explain whether it can be sent to the mailbox, thank you。

**Comment by sandipnlakhani** [comment]
Hello Greetings, Love from India 🇮🇳 How to Resubmit Kyc Details?
