### ISSUE TITLE
pi

### ISSUE THREAD

**Issue by beling330** [pi-apps/pi-platform-docs#143]
**
**

**Comment by Albertemmanuelkesuanu** [comment]
Hi

**Comment by Mkay21** [comment]
Hi

**Comment by Yashwantsinghraakawat** [comment]
Yes I am here to hear you.

On Saturday, May 7, 2022, Mkay21 ***@***.***> wrote:
> Hi
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci4.googleusercontent.com/proxy/flsz8URKc2BhpqoAVdQs3RDIQ8uH7ysTsZDniioyLYOP7mnHP2_uzZDEUiv23OWbCt-2vMmWvD1UucpwfeLb38Lq4lzEAlIl-x_emy7vMMLLGYf-I_tZ_iEb-Usgct-liTJWwcL_LDdc1wvlh9ioIdxa4tmzvVjrJ_9DzLO9ZfFwQQYW80tIZ-jY0cKeFICJFpsOmJnJweu7-mzJ8sdQB7L6vg25HbYeHURvKU2bBw=s0-d-e1-ft#https://github.com/notifications/beacon/AV46W4HNQII3U6VKPUMEGKLVIYNTRA5CNFSM5SNE7ASKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOILCECPI.gif>Message
ID: ***@***.***>

**Comment by 0292568684** [comment]
Vere good

**Comment by Yashwantsinghraakawat** [comment]
On Friday, May 13, 2022, 0292568684 ***@***.***> wrote:
> Vere good
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci6.googleusercontent.com/proxy/vrnpx9Palb4YYCZoJ6rrOwi3wGEOVtnpc77814Ae6GS6BQC2t8Aos1J6df0H9nv6cVRKhW8HFsDW4wFKW77Tp-Mf8UQfnJZsT1xbUgSlX2N9xfGk2ZFXh6UDpPjUVPHHBLCnwFcfWatqLnONYKIMh69RTHIWM7suzBdGHn60W4izZ08P7iy6w6eSD53deUMFIYsJFyzBYQqIXZtVXLWRHgM_ufZFxMxClyhy49uxoA=s0-d-e1-ft#https://github.com/notifications/beacon/AV46W4BDEBIVVQC5ODSFRTLVJZFINA5CNFSM5SNE7ASKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOIMO23WY.gif>Message
ID: ***@***.***>

**Comment by Albertemmanuelkesuanu** [comment]
How you doing
