### ISSUE TITLE
Happy user

### ISSUE THREAD

**Issue by jhadhiraj774** [pi-apps/pi-platform-docs#15]
Loving this application..

**Comment by Jahangirami** [comment]
I love this app

**Comment by Jahangirami** [comment]
Pi network is a very good app I hope this moon will cover the world like bitcoin in months

**Comment by Sten435** [comment]
Hello,
Its nice to hear that you like the app but this section is about issues reguarding the PI SDK.

This is conciderd as spam !

You can share you feedback on the chats on the pi app.

Greetings
Stan p

**Comment by EstherSarianSow** [comment]
I love this app

**Comment by muhammadhussainmahar** [comment]
Pi who is lanch is pakistan
