### ISSUE TITLE
Sandbox is not working. https://sandbox.minepi.com/

### ISSUE THREAD

**Issue by aarrtturas** [pi-apps/pi-platform-docs#156]
Hi, sandbox page is not working  https://sandbox.minepi.com/. Message "This page is not accessible on this app."

**Comment by Jbabdul** [comment]
Check your network 
Or you try again later

**Comment by hklee93** [comment]
Hi, sandbox is provided to run your app for testing. Once you create your app within the Developer Portal, it will show you the sandbox url that you can use within the desktop browser. Feel free to open a new issue. Thanks!
