### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Hyundaisunil** [pi-apps/pi-platform-docs#16]
What is this ?? I am not getting it

**Comment by Mushe60** [comment]
You are not supposed to know anything

**Comment by Son120783** [comment]
Ok

**Comment by Sadisuumar77** [comment]
I don't know how to use, this set please help me

**Comment by aszasz1234** [comment]
All of the work now is check the payment system by third party developers https://user-images.githubusercontent.com/74979251/123906049-0e247180-d9a6-11eb-9b7a-56fea0984b38.MOV

**Comment by FazalAmin1986** [comment]
Ok

**Comment by Madhurmila44** [comment]
Yes you can know all things

**Comment by FazalAmin1986** [comment]
I don't understand.whats it's mean s

**Comment by FazalAmin1986** [comment]
Someone tell me what is this?

**Comment by dannybutterfield1880** [comment]
This github repository is for people who want to build there own pi network apps and integrate the software development kit.

**Comment by Sten435** [comment]
Don't open issues for items that have notting to do with the SDK!

If you have questions about Pi, i would advise you to look in to the pi application...

Greetings.
