### ISSUE TITLE
Hajii0092

### ISSUE THREAD

**Issue by Hajii0092** [pi-apps/pi-platform-docs#18]

**Comment by Hajii0092** [comment]
Mohammadaminhajizadeh

**Comment by FazalAmin1986** [comment]
Hi

**Comment by dannybutterfield1880** [comment]
Please don't use this github project as a chatroom. It is for people who are having an issue using the SDK.

**Comment by Sten435** [comment]
Danny's right

@Hajii0092 please close this issue.

Greetings
