### ISSUE TITLE
Can't figure out what happend

### ISSUE THREAD

**Issue by aszasz1234** [pi-apps/pi-platform-docs#2]
![S__4120976](https://user-images.githubusercontent.com/74979251/123727841-de516d00-d8c4-11eb-8665-2d3439590766.jpg)

After I change my domain , before changing it is working well for me

**Comment by SuperHax** [comment]
I got the same problem,are u fix that?

**Comment by aszasz1234** [comment]
@SuperHax When did you thought this problem?

**Comment by SuperHax** [comment]
when I change my domain,

**Comment by aszasz1234** [comment]
@SuperHax Try this Pi.init({version="2.0"})

**Comment by SuperHax** [comment]
thx ,now is working, i add Pi.init({version:"2.0"}) in my code
