### ISSUE TITLE
messaging promise with id 3 timed out after 60000ms. what problem with this message?

### ISSUE THREAD

**Issue by SuperHax** [pi-apps/pi-platform-docs#21]

**Comment by mitjans** [comment]
What browser are you using to test your app? It has to bee Pi Browser.
Check issue #11

**Comment by SuperHax** [comment]
> What browser are you using to test your app? It has to bee Pi Browser.
> Check issue #11

yes ,i useing pi browser

**Comment by SuperHax** [comment]
> What browser are you using to test your app? It has to bee Pi Browser.
> Check issue #11

const scopes = ['payments'];
var uid = 0;
function onIncompletePaymentFound(payment) { /* ... */ }; // Read more about this in the SDK reference

Pi.authenticate(scopes, onIncompletePaymentFound).then(function(auth) {
   
  console.log(`Hi there! You're ready to make payments!`);
}).catch(function(error) {
  console.error(error);
});
           
const payment = Pi.createPayment({
  // Payment data:
 
  "amount": 1, // The payment amount
  "memo": "test", // A string provided by the developer, shown to the user
  "metadata": { orderId: 1234}, // An object provided by the developer for their own usage
 // The payment's creation timestamp

}, {
  // Callbacks you need to implement - read more about those in the detailed docs linked below:
  onReadyForServerApproval: function(paymentId) {},
  onReadyForServerCompletion: function(paymentId, txid) { /* ... */ },
  onCancel: function(paymentId) { /* ... */ },
  onError: function(error, payment) { /* ... */ alert(error)},
});
          
        })

**Comment by SuperHax** [comment]
> What browser are you using to test your app? It has to bee Pi Browser.
> Check issue #11

my code here ,can u help me to check it out?

**Comment by aszasz1234** [comment]
Your code only create payment that is the first step, you need to approve the payment to pi server> > What browser are you using to test your app? It has to bee Pi Browser.
> 
> > Check issue #11
> 
> 
> 
> my code here ,can u help me to check it out?

**Comment by Sten435** [comment]
You can view this for more informatiob about step: 2 and step: 3.

Geetings

**Comment by SuperHax** [comment]
> Your code only create payment that is the first step, you need to approve the payment to pi server
> 
> > > Check issue #11
> > 
> > 
> > my code here ,can u help me to check it out?

in server site i need to post paymentid to this url "https://minepi.com/payments/:payment_id/approve "?

**Comment by aszasz1234** [comment]
Yes, need to change:payment _id that you get from callback function, and make sure your post to pi server need a header contain api key
> 
> > 
> 
> > > > Check issue #11
> 
> > > 
> 
> > > 
> 
> > > my code here ,can u help me to check it out?
> 
> 
> 
> in server site i need to post paymentid to this url "https://api.minepi.com/v2/payments/:payment_id/approve "?

**Comment by RanaAhmed2020** [comment]
My code here, can u help me?

**Comment by Sten435** [comment]
@RanaAhmed2020 whats upp, whats your problem ?

**Comment by SuperHax** [comment]
> Yes, need to change:payment _id that you get from callback function, and make sure your post to pi server need a header contain api key
> 
> > > 
> > 
> > 
> > > > > Check issue #11
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > my code here ,can u help me to check it out?
> > 
> > 
> > in server site i need to post paymentid to this url "https://api.minepi.com/v2/payments/:payment_id/approve "?

thank u , i solved the problem

**Comment by wrramerson** [comment]
como vc resolvel o problema?
estou tendo o mesmo problema
