### ISSUE TITLE
Updating an app name in Pi Developer Portal

### ISSUE THREAD

**Issue by SHADYKIMBUM** [pi-apps/pi-platform-docs#231]
I'm not sure what you'd like to change here. Is it the domain name (the string that appears in the Pi Browser's address bar - "brainstorm.pi" in the screenshot below)? Or is it the name that appears in the gray bar on top of your app ("Brainstorm" in the screenshot below)?

![IMG_0251](https://user-images.githubusercontent.com/14823737/124572304-d8213a80-de48-11eb-83de-4b3864a5dbbf.jpg)

The "user-friendly" name can be changed by updating the app on the developer portal.

You can change to a different domain name after deploying your app on the new domain, by updating the app on the developer portal accordingly. You'll have to go through the ownership verification for the new domain name. FYI, it is not possible for third-party developers to get .pi domain names at the moment.

_Originally posted by @aurelienshz in https://github.com/pi-apps/pi-platform-docs/issues/47#issuecomment-874589031_

**Comment by hklee93** [comment]
Hi @SHADYKIMBUM , can you clarify your question a bit? If you want to update your app name, you can simply go to pi://develop.pi in the Pi Browser and update the app name accordingly.

**Comment by SHADYKIMBUM** [comment]
![D2D5B9D1-4729-48AE-83E8-29C0DF71E255](https://user-images.githubusercontent.com/37724858/185915838-07d6ddde-7d03-4995-b03d-9141c5c43b9e.png)

![B1645A26-C48C-42CA-9178-6B5F7D6BC8C6](https://user-images.githubusercontent.com/37724858/185915868-4ee3d2a8-fdb9-4e19-8b5b-3880e6c1b364.png)


Help me work

**Comment by SHADYKIMBUM** [comment]
![Uploading E714F3E1-8970-4352-95FA-9C12BD31DB10.png…]()

**Comment by sdkosm** [comment]
I ma also unable to question properly. Can you explain a bit more ?
