### ISSUE TITLE
Need some suggestion on setting up Pi Node

### ISSUE THREAD

**Issue by nilkamhaeng** [pi-apps/pi-platform-docs#234]
I've setup Pi Node on Windows 10. I've done all processes that I watched from Youtube. However, I still feel it's not compete setup yet.

My node condition are these;
* Port open only 2 ports 31401 and 31403
* Starting ports listener still in grey color
* Pinging your computer still in red
* Incoming connections still indicates  0
* Supporting other nodes still  No

Any one has the same issue as I have, please suggest what else I need to do. 
Thank you in advance,

![pi doc](https://user-images.githubusercontent.com/111557934/185554956-de8974ab-ecf0-400a-bc68-4dfc4f8f5d45.jpg)
![github](https://user-images.githubusercontent.com/111557934/185554977-241880ac-9a9c-48ce-a9f8-eee9f7e1a507.jpg)

**Comment by Thorisol** [comment]
Uninstall it and rerun the Pi Node software..

**Comment by hklee93** [comment]
Hi, please reach out to [Pi Support Portal](https://pinetwork.atlassian.net/servicedesk/customer/portals) for node question.
