### ISSUE TITLE
Does a Authorization: Bearer <user access token> work with the payment API ?

### ISSUE THREAD

**Issue by Sten435** [pi-apps/pi-platform-docs#24]
On the 'Platform API,' it said that there are 2 methods of authorization.

But when I scroll down to the payment references, I see that the description says 'Authorization method: **Server API Key**'

Does this mean that a Bearer token can not be used with the payment API?
This is weird because at the top of the page it says that there are 2 methods of verification.

I ask this because I'm trying to do a test payment but it does not work.

You can see my code 👇👇👇

```
window.Pi.authenticate(scopes, onIncompletePaymentFound).then(function (auth) {
        document.getElementById('pay-pi_button').addEventListener('click', () => {
            Pi.createPayment({
                amount: 3.14,
                memo: "This is the description.",
                metadata: { data: "This is a test object." },
            }, {
                onReadyForServerApproval: function (paymentId) { ApiRequest({ user_token: auth.accessToken, method: 'POST', paymentId, endPath: 'approve', txid: '' }) },
                onReadyForServerCompletion: function (paymentId, txid) { ApiRequest({ user_token: auth.accessToken, method: 'POST', paymentId, endPath: 'complete', txid }) },
                onCancel: function (paymentId) { },
                onError: function (error, payment) { },
            });
        })

    }).catch(function (error) {
        alert(error)
    });

    function ApiRequest(data) {
        let basepath = "api.minepi.com/v2"
        fetch(`${basepath}/payments/${data.paymentId}/${data.endPath}`, {
            method: data.method,
            headers: {
                "Authorization": `Bearer ${data.user_token}`
            },
            body: {
                "txid": data.txid
            }
        })
    }
```

**Comment by aszasz1234** [comment]
> On the 'Platform API,' it said that there are 2 methods of authorization.
> 
> 
> 
> But when I scroll down to the payment references, I see that the description says 'Authorization method: **Server API Key**'
> 
> 
> 
> Does this mean that a Bearer token can not be used with the payment API?
> 
> This is weird because at the top of the page it says that there are 2 methods of verification.
> 
> 
> 
> I ask this because I'm trying to do a test payment but it does not work.
> 
> 
> 
> You can see my code 👇👇👇
> 
> 
> 
> ```
> 
> window.Pi.authenticate(scopes, onIncompletePaymentFound).then(function (auth) {
> 
>         document.getElementById('pay-pi_button').addEventListener('click', () => {
> 
>             Pi.createPayment({
> 
>                 amount: 3.14,
> 
>                 memo: "This is the description.",
> 
>                 metadata: { data: "This is a test object." },
> 
>             }, {
> 
>                 onReadyForServerApproval: function (paymentId) { ApiRequest({ user_token: auth.accessToken, method: 'POST', paymentId, endPath: 'approve', txid: '' }) },
> 
>                 onReadyForServerCompletion: function (paymentId, txid) { ApiRequest({ user_token: auth.accessToken, method: 'POST', paymentId, endPath: 'complete', txid }) },
> 
>                 onCancel: function (paymentId) { },
> 
>                 onError: function (error, payment) { },
> 
>             });
> 
>         })
> 
> 
> 
>     }).catch(function (error) {
> 
>         alert(error)
> 
>     });
> 
> 
> 
>     function ApiRequest(data) {
> 
>         let basepath = "api.minepi.com/v2"
> 
>         fetch(`${basepath}/payments/${data.paymentId}/${data.endPath}`, {
> 
>             method: data.method,
> 
>             headers: {
> 
>                 "Authorization": `Bearer ${data.user_token}`
> 
>             },
> 
>             body: {
> 
>                 "txid": data.txid
> 
>             }
> 
>         })
> 
>     }
> 
> ```

No , only like the document said, and mention you that the post should send from your server to pi server or your api key will be seen.

**Comment by Sten435** [comment]
Aha, thanks.
So we need a server to do the payments atm.
Greetings
