### ISSUE TITLE
Pi Init Got some Error Version

### ISSUE THREAD

**Issue by bambangSiS** [pi-apps/pi-platform-docs#242]
Basicly, i create html and put di source <script>Pi.init({ version: "2.0" })</script> 
my console saw 

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://app-cdn.minepi.com') does not match the recipient window's origin (my website)

**Comment by TheGeniusGeek** [comment]
I have the same problem

**Comment by TheGeniusGeek** [comment]
> Basicly, i create html and put di source <script>Pi.init({ version: "2.0" })</script> 
> 
> my console saw 
> 
> 
> 
> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://app-cdn.minepi.com') does not match the recipient window's origin (my website)

I think that You have this error because you run your app on another browser except Pi browser.
To fix the problem run your app in the pi Sandbox and open console to see the Magic ✨
