### ISSUE TITLE
.net implementation 

### ISSUE THREAD

**Issue by perfect-angle** [pi-apps/pi-platform-docs#259]
Hi folks,

can anyone please help me , how can i integrate pi-nework payment with my application.

i already created app in pi-nework and i am able to authenticate user also but regarding payment approve and complete i am stuck , anyone please help me how can i intiate payment and approve from server side and pass to block user and complete payment.

**Comment by hklee93** [comment]
Hi, please elaborate a bit where you're getting stuck. Make sure you're requesting the payment scope when you authenticate, so that you can create a payment. Feel free to reopen the issue.
