### ISSUE TITLE
`Pi.openConversation` usage?

### ISSUE THREAD

**Issue by SHADYKIMBUM** [pi-apps/pi-platform-docs#261]
I'm not 100% sure on how `Pi.openConversation` works (although I think I might have a basic idea?), but hopefully one of the Pi Apps Platform devs can propose any changes here so that the documentation includes all available methods. It's probably a good idea to have the documentation there even if the feature is simply exposed in the JavaScript SDK but not yet fully implemented (why I put a "Coming Soon" notice, which I can delete if necessary) so that developers can start planning features. Please let me know what you think. 

__Originally posted by @CMEONE in https://github.com/pi-apps/pi-platform-docs/pull/68__

**Comment by Niaga16** [comment]
Oke

Ahmad Niaga

Pada tanggal Sen, 3 Okt 2022 16.36, SHADYKIMBUM ***@***.***>
menulis:

**Comment by hklee93** [comment]
Hi, thanks for reaching out. `openConversation` is only being used internally at the moment. We'd need to create a conversation for you in advance if you wanted to use this function, which is why we call it for internal usage.
