### ISSUE TITLE
API for send money ?

### ISSUE THREAD

**Issue by perfect-angle** [pi-apps/pi-platform-docs#264]
I want to send money to end user from API , Is there any API for that ?

**Comment by 0205miss** [comment]
You can use horizon api from node or stellarSDK to help you.

**Comment by skaanild** [comment]
> You can use horizon api from node or stellarSDK to help you.

@0205miss Can you elaborate a bit more? Maybe share an example?

**Comment by hklee93** [comment]
Hi, we have this feature standing in our pipeline, along with the updated document. Hopefully we can unblock you soon.

**Comment by perfect-angle** [comment]
Can we send money directly to wallet id?

**Comment by perfect-angle** [comment]
Can we send PI directly to public wallet id account ?
