### ISSUE TITLE
How to send Payment?

### ISSUE THREAD

**Issue by Frogleim** [pi-apps/pi-platform-docs#265]
Who can tell me , is it possible to send payment via SDK?(Javascript)

**Comment by ronielex** [comment]
No

**Comment by hklee93** [comment]
Hi, using the SDK, you can process a user-to-app payment type at the moment. Please refer to the document and if you encounter any issue, let us know.

**Comment by Frogleim** [comment]
> Hi, using the SDK, you can process a user-to-app payment type at the moment. Please refer to the document and if you encounter any issue, let us know. 

So, I can send my Pi coins to other user? I want to write script for that
