### ISSUE TITLE
Is "Server API key" the key obtained in the develop.pi ?

### ISSUE THREAD

**Issue by TheGeniusGeek** [pi-apps/pi-platform-docs#266]
To approve a payelent we must make a post request with header { xxxxxx : "key ${Server API KEY}"}

is the Server API KEY The key that we got in develop.pi ?? or we should use our own server API KEY

**Comment by hklee93** [comment]
Hi, yes you can generate the API Key in the Pi Developer Portal (develop.pi on the Pi Browser).
