### ISSUE TITLE
[question] is it possible to authenticate a user from the back-end ?

### ISSUE THREAD

**Issue by Smoqqqq** [pi-apps/pi-platform-docs#267]
Hi,

I would like to try to create a PI app (test), and i'd like to do so in Symfony (PHP).
Is it possible to do so, or is it only possible using front-end JS ?

Thanks !

**Comment by rockcesar** [comment]
Yes, you can. With the endpoint in the URL:

https://api.minepi.com/v2/me

Here is the documentation:

https://github.com/pi-apps/pi-platform-docs/blob/master/platform_API.md

But the access point you have to get it from the Frontend in Pi.authenticate.
