### ISSUE TITLE
Error 500: We're sorry, but something went wrong (500)

### ISSUE THREAD

**Issue by vidaniello** [pi-apps/pi-platform-docs#27]
Server-side:

REQUEST RAW

POST /v2/payments/:wmsuEPgPVmHELIuvji7xrudeAUw5/approve HTTP/1.1
Authorization: key l7o0qh1tls.............................................................................................................................
Host: api.minepi.com
Content-Type: application/json
Content-Length: 0

RESPONSE RAW

HTTP/1.1 500 Internal Server Error
content-type: text/html; charset=UTF-8
content-length: 1635
status: 500 Internal Server Error
vary: Origin
x-request-id: aac6a1b6-ecb4-492f-b41a-a14e70ddc19d
x-runtime: 0.022898
date: Wed, 30 Jun 2021 15:21:29 GMT
x-powered-by: Phusion Passenger 6.0.6
server: nginx/1.14.0 + Phusion Passenger 6.0.6

<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  .rails-default-error-page {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  .rails-default-error-page div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  .rails-default-error-page div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  .rails-default-error-page h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  .rails-default-error-page div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body class="rails-default-error-page">
  
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

**Comment by aurelienshz** [comment]
I think the path to which you're making the request is wrong: `/v2/payments/:wmsuEPgPVmHELIuvji7xrudeAUw5/approve`

You have an extra `:` before the payment id. This should probably be `/v2/payments/wmsuEPgPVmHELIuvji7xrudeAUw5/approve`.

I think the confusion came from the fact that the documentation marks the path argument as `:payment_id`. Would it have been clearer to write something like this?

`POST /payments/{payment_id}/approve`

**Comment by Sten435** [comment]
@aurelienshz yea with the brackets is way clearer.
I made the same misstake earlyer.

**Comment by Sten435** [comment]
@vidaniello i have a question for you about this project. I cant find a way to contact you so can you add me on discord: 

**Stan Persoons#1772**

Or via E-mail: _stan@persoons.tech_

**Comment by Ayazalinarejo** [comment]
Ok

**Comment by Madhurmila44** [comment]
Yes I am receiving it

**Comment by Madhurmila44** [comment]
Thank you developer

**Comment by Madhurmila44** [comment]
I am from India

**Comment by vidaniello** [comment]
@aurelienshz Ok, tanks! without `:` it work.
@Sten435 about which project? pi chain or mine? about my project I can anticipate that it is a simple test to experiment with the pi blockchain.

**Comment by Sten435** [comment]
> @aurelienshz Ok, tanks! without `:` it work.
> @Sten435 about which project? pi chain or mine? about my project I can anticipate that it is a simple test to experiment with the pi blockchain.

About how you connect to the pi network API and what data you can see. for example can you see the users amount of pi ?
Greetings

**Comment by Sten435** [comment]
The endpoint i use does not exist: **https://api.minepi.com/v2/payments/**

What endpoint do you to get the payment info?
Greetings

**Comment by vidaniello** [comment]
@Sten435 Ok, see my test as an example here: [donatepi.glitch.me:EDIT](https://glitch.com/edit/#!/donatepi?path=index.html%3A1%3A0)
 regarding the other functions of the blockchain, such as the wallet total, I think we have to wait for indications in [this github](https://github.com/pi-apps/pi-platform-docs) project; @aurelienshz is that so?
@Sten435 the endpoint of payment is 

GET /v2/payments/_payment-id_
Authorization: key l7o0qh1tls.............................................................................................................................
Host: api.minepi.com

for the auth key, read the instruction  from the app _develop.pi_ on the pi browser on your phone.

[read here the documentation](https://github.com/pi-apps/pi-platform-docs/blob/master/platform_API.md) about the actual api commands, test with [online http reuests](https://reqbin.com/) for the call who made server side, or directly from the UI interface, but that it is only for testing as the developers of pi have been clear about it..

**Comment by Sten435** [comment]
Thank you so much, but how do you test the online HTTP request? because you need the payment id and you can get that only from the mobile py browser? Do you type in into your computer on that site to test the HTTP request ?

Greetings

**Comment by Sten435** [comment]
> @Sten435 Ok, see my test as an example here: [donatepi.glitch.me:EDIT](https://glitch.com/edit/#!/donatepi?path=index.html%3A1%3A0)
> regarding the other functions of the blockchain, such as the wallet total, I think we have to wait for indications in [this github](https://github.com/pi-apps/pi-platform-docs) project; @aurelienshz is that so?
> @Sten435 the endpoint of payment is
> 
> GET /v2/payments/_payment-id_
> Authorization: key l7o0qh1tls.............................................................................................................................
> Host: api.minepi.com
> 
> for the auth key, read the instruction from the app _develop.pi_ on the pi browser on your phone.
> 
> [read here the documentation](https://github.com/pi-apps/pi-platform-docs/blob/master/platform_API.md) about the actual API commands, test with [online HTTP reuests](https://reqbin.com/) for the call who made server-side, or directly from the UI interface, but that it is only for testing as the developers of pi have been clear about it.

Strange but it does not work, I get the same result as you. (this issue) you can see my error here: #29

**Comment by Madhurmila44** [comment]
Thank you sir for informed me

**Comment by Madhurmila44** [comment]
Your opinion wait is correct for us

**Comment by vidaniello** [comment]
See here an example of app: https://github.com/vidaniello/donatepi-app
And here an example of server: https://github.com/vidaniello/donatepi-server
All work for me!!
In the README.md of theese repo there are the link to glitch.com running environments.
