### ISSUE TITLE
How to work with api.testnet.minepi.com?

### ISSUE THREAD

**Issue by Frogleim** [pi-apps/pi-platform-docs#273]
Hi everyone! 
I trying to use api.testnet.minepi.com, but there is no good documantation for that! For example I want to send payment with, how? I want to check payments, aga how? 
Documantation is empty! 
For example I found this url 
https://api.mainnet.minepi.com/paths/strict-send{?destination_account,destination_assets,source_asset_type,source_asset_issuer,source_asset_code,source_amount}
and I there are many questions 
1. What is strict-send?
2. What is destination_assets?
3. source_asset_issuer?
4. source_asset_code?
And there many questions like this! If you want to create product please be carefull with client side! and give us some explanations

**Comment by TheGeniusGeek** [comment]
Type the url on your browser you will see all the different endpoints that you can use...
exemple: https://api.testnet.minepi.com/accounts/{account_id}(To fetch account infos), https://api.testnet.minepi.com/fee_stats(To fetch fee stats)

to see the mainnet api endpoints use this url: https://api.mainnet.minepi.com
