### ISSUE TITLE
Retrieve Operations with the transaction hash

### ISSUE THREAD

**Issue by RichAdams0x** [pi-apps/pi-platform-docs#275]
When we make a payment with Pi.createPayment, if it finishes successfully, we got two infos : The tx hash and the paymentId...
With the transaction hash we have not access to the amount paid during the payment (When fetching at "https://api.testnet.minepi.com/transactions/{TXID}")...
but in my project I need to access the payment amount by using the txId...(I want to perform some additional security checks...)
So the solution that I found is:
Within the data gathered during the fetch at {https://api.testnet.minepi.com/transactions/{TXID}}, we have a field called **### paging_token**... I remaked that the value of this field correspond to the "Self" of the operation corresponding to this transaction...
exemple:
TX(Transaction)--->paging_token:10
OP(Operation)-->id:11
**==> OP(id) = TX(paging_token)+1**
so to retrieve the operation data with the TxHash we must:
get the paging_token from the txData (The data is obtained during fetch)
then fetch the corresponding operation : https://api.testnet.minepi.com/operations/{PAGING_TOKEN +1}
My question is: Am I right ?
And : if I am right I think that this works only when the transaction contain only one operation

**Comment by Niaga16** [comment]
Yes

Ahmad Niaga

Pada tanggal Rab, 23 Nov 2022 22.12, Omega ***@***.***>
menulis:

**Comment by aurelienshz** [comment]
@RichAdams0x you do not need to use the paging token. You can directly pull the operations included in a transaction with the /transactions/:txid/operations endpoint, e.g:

https://api.testnet.minepi.com/transactions/9b7b8ee35311714d75ed439cf7447f82e652be2b38bc268cae010a820ae767b9/operations
