### ISSUE TITLE
That domain verification api reports an error：Something went wrong. Please try again.

### ISSUE THREAD

**Issue by wanlinqiang** [pi-apps/pi-platform-docs#279]
Api: https://socialchain.app/portal/third_party_apps/xxxxxxxxxxxxxxxxxxxxxx/verify
Status: 500 Internal Server Error

**Comment by Daibao9999** [comment]
> Api: https://socialchain.app/portal/third_party_apps/xxxxxxxxxxxxxxxxxxxxxx/verify
> 
> Status: 500 Internal Server Error
