### ISSUE TITLE
How to check whether the user is using the pi browser？

### ISSUE THREAD

**Issue by li41** [pi-apps/pi-platform-docs#285]
How to check whether the user is using the pi browser？

**Comment by Daibao9999** [comment]
[]()

**Comment by Daibao9999** [comment]
<script src="https://sdk.minepi.com/pi-sdk.js"></script>
<script>Pi.init({ version: "2.0" })</script>
The

**Comment by 0205miss** [comment]
You can try to use web socket.

**Comment by li41** [comment]
My idea is to use the following judge, but it is not suitable for Pi Testnet

if(navigator. userAgent. search("PiBrowser") > -1) {
   ...
} else {
   ...
}

**Comment by kplybae25** [comment]
Berhenti

Pada tanggal Jum, 23 Des 2022 09.31, 李世逸 ***@***.***> menulis:

**Comment by 0205miss** [comment]
> My idea is to use the following judge, but it is not suitable for Pi Testnet
> 
> 
> 
> if(navigator. userAgent. search("PiBrowser") > -1) {
> 
>    ...
> 
> } else {
> 
>    ...
> 
> }
This is working fine on PiBrowser both in Testnet app and Mainnet app
