### ISSUE TITLE
HTTP/1.1 500 Internal Server Error at POST /payments/:payment_id/approve

### ISSUE THREAD

**Issue by Sten435** [pi-apps/pi-platform-docs#29]
When I want to post with the **paymentId** to _https://api.minepi.com/v2/payments/SomeRandomPaymentId/approve_ I get the error below the data that I sent:

### **DATA that I send to the API.**
```
POST /v2/payments/PR1qHuKAjgfMDs5WB9DdFoHiq3I6/approve HTTP/1.1
Host: api.minepi.com
Authorization: Key uc7jkx................................................................................
```

### **DATA that the API sends back to me:**

```
- HTTP/1.1 500 Internal Server Error
- content-type: text/html; charset=UTF-8
- content-length: 1635
- status: 500 Internal Server Error
- vary: Origin
- x-request-id: e68ad09d-2a79-4776-a71a-b6444181d01f
- x-runtime: 0.020006
- date: Wed, 30 Jun 2021 23:38:31 GMT
- x-powered-by: Phusion Passenger 6.0.6
- server: nginx/1.14.0 + Phusion Passenger 6.0.6
```

```
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  .rails-default-error-page {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  .rails-default-error-page div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  .rails-default-error-page div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  .rails-default-error-page h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  .rails-default-error-page div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body class="rails-default-error-page">
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>
```

### **These are the headers that the server with error code 500 sends back to me:**

```
- content-type: text/html; charset=UTF-8
- content-length: 1635
- status: 500 Internal Server Error
- vary: Origin
- x-request-id: e68ad09d-2a79-4776-a71a-b6444181d01f
- x-runtime: 0.020006
- date: Wed, 30 Jun 2021 23:38:31 GMT
- x-powered-by: Phusion Passenger 6.0.6
- server: nginx/1.14.0 + Phusion Passenger 6.0.6
```

### **Some more information:**

```
- Status:
- 500 (Internal Server Error)
- Time:
- 1686 ms
- Size:
- 1.60 kb
```

<img width="577" alt="Schermafbeelding 2021-07-01 om 01 54 57" src="https://user-images.githubusercontent.com/44066744/124045154-5e83e980-da0f-11eb-834a-62aac36df1a5.png">

This is an error on the API I hope this information is clear and that the error will be fixed soon. 👍
I hope this will be seen as urgent as this is a big problem with the API. @aurelienshz 

Greetings.

**Comment by n37r09u3** [comment]
same error

**Comment by aszasz1234** [comment]
I can post successfully....By using python request package

**Comment by NadeemDxb** [comment]
Yes it's true

**Comment by Sten435** [comment]
> I can post successfully....By using python request package 

@aszasz1234 Can you share your output with us?

And possibly your code ?

**Comment by Sten435** [comment]
I tried it with PHP and JS both give me the error.

**Comment by aszasz1234** [comment]
In python:
requests.post(url,
        headers={'Authorization':'Key APIKEY'})

**Comment by Sten435** [comment]
> In python:
> requests.post(url,
>         headers={'Authorization':'Key APIKEY'})

What response do you get?

**Comment by aszasz1234** [comment]
> > In python:
> > requests.post(url,
> > headers={'Authorization':'Key APIKEY'})
> 
> What response do you get?

Same as the document under the platform_api page

**Comment by vcyk** [comment]
> > > In python:
> > > requests.post(url,
> > > headers={'Authorization':'Key APIKEY'})
> > 
> > 
> > What response do you get?
> 
> Same as the document under the platform_api page

Is url with or without colon after /payments/

**Comment by vcyk** [comment]
> I tried it with PHP and JS both give me the error.

Has the error been resolved ?

**Comment by Sten435** [comment]
@vcyk its without the ```:```

**Comment by Sten435** [comment]
> > I tried it with PHP and JS both give me the error.
> 
> Has the error been resolved ?

The error has **not been** resolved at 01/07 - 14:27

**Comment by dannybutterfield1880** [comment]
@Sten435 I've got everything working I'll share a guide in a couple of hours using JavaScript (node), express and axios for the request

**Comment by Sten435** [comment]
> @Sten435 I've got everything working I'll share a guide in a couple of hours using JavaScript (node), express and axios for the request

Thanks, bud 👍

**Comment by Sten435** [comment]
> @Sten435 I've got everything working I'll share a guide in a couple of hours using JavaScript (node), express and axios for the request 

So are all the endpoints working correctly?

Greetings
Stan P

**Comment by dannybutterfield1880** [comment]
[FirePi/functions](https://github.com/dannybutterfield1880/fire-pi-base/tree/main/functions) have a look at this directory I am working on. It is not finished yet and is taking some time. But when its finished this will be a full base code to build a firebase + Pi network + react app. I will extract the Pi network parts of this code and make more simple server side example once I have finished this set up.

**Comment by dannybutterfield1880** [comment]
The way it is set up we would only be required to modify the handler.js methods to do something with the response from pi's servers. I am writing a detailed guide but will take some time

**Comment by dannybutterfield1880** [comment]
basically the api.js file is creating endpoints on your server side which you can then call from your client side using POST https://your-api-url/api/v1/payments/approve and you would need to pass paymentId to the body of this request

**Comment by dannybutterfield1880** [comment]
I am also now getting this error in my second project FirePi #36

**Comment by dannybutterfield1880** [comment]
@Sten435  I have a working version now at [https://pi-services-f7f6f--uat-6nq6u5qi.web.app/#/](https://pi-services-f7f6f--uat-6nq6u5qi.web.app/#/) the payment process will start on page load and it completed successfully. Now its all working ill sort a proper guide out. Just didn't want to misinform people

**Comment by Sten435** [comment]
@dannybutterfield1880 your application not working on my end.

![Screenshot_20210702-151242.jpg](https://user-images.githubusercontent.com/44066744/124279625-043a7400-db48-11eb-8808-d4a7e291ab4e.jpg)

**Comment by dannybutterfield1880** [comment]
@Sten435 that is strange. Try firepi-react.web.app I've also just got that working. Maybe it's an issue with your Pi browser app have you tried reinstalling or using a different device?

**Comment by dannybutterfield1880** [comment]
Are you using a VPN, tunnelling or proxy or anything like that?

**Comment by Sten435** [comment]
Thanks, i will try reinstaling.

**Comment by Sten435** [comment]
> Are you using a VPN, tunnelling or proxy or anything like that?

No im not using tunnels or vpn or proxy.

**Comment by NadeemDxb** [comment]
It's not working URL:

**Comment by dannybutterfield1880** [comment]
[https://firepi-react.web.app](Fire Pi)

Not sure if the link will work as I'm in my phone

**Comment by dannybutterfield1880** [comment]
@Sten435 I'm not sure about that error I haven't come across it yet just fishing for ideas of why it may be

**Comment by dannybutterfield1880** [comment]
@NadeemDxb Just realised the github link doesn't work, do you mean that?

https://github.com/dannybutterfield1880/fire-pi-base

**Comment by rockcesar** [comment]
Check this server side PHP example:

https://github.com/rockcesar/PiNetworkDevelopments/blob/master/server1.php

**Comment by rockcesar** [comment]
There is a Python3 Server side example, made in Odoo, that is almost pure Python3:

https://github.com/rockcesar/PiNetworkDevelopments/blob/master/website_pinetwork_odoo/controllers/main.py

**Comment by Sten435** [comment]
If anyone has questions about the Pi Network SDK or other general coding questions regarding anything related to the Pi Network, then you ask them in the Pi Network Developer Portal: https://discord.gg/qM3fXPq4fK
It is a faster way to connect with people, instead of contact people through email, or through the Pi chat app, which can be a real pain.

This is not an AD, this is an informative post for people who may need a communication server for a question.

**Comment by Sten435** [comment]
As of now 06/07 This bug seems fixed, lat me know if anywane has this error.

Il close this issue for now.

**Comment by 81888** [comment]
这个问题并没有被解决。

**Comment by hklee93** [comment]
@81888 what's the issue you're experiencing?
