### ISSUE TITLE
Kyc dan penambahan nomor telepon

### ISSUE THREAD

**Issue by muhikhwan93** [pi-apps/pi-platform-docs#292]
Susah sekali untuk melakukan verifikasi data dan pendaftaran nomor telepon

**Comment by Mamatbat** [comment]
Masuk google play download PULSE SMS

Pada Aha, 1 Jan 2023 01:12 Muhamad Ikhwan ***@***.***>
menulis:

**Comment by adizioloo** [comment]
Dziuba Adam kyc  weryfikacji

**Comment by Salisukk** [comment]
I didn't have kyc up to now

**Comment by sadamahid** [comment]
لم ياتي التوثيق كيف اوثق حسابي
