### ISSUE TITLE
Cannot create a payment without "payments" scope Error

### ISSUE THREAD

**Issue by aarrtturas** [pi-apps/pi-platform-docs#304]
I get this message then I try to create payment from my own account. It was working before not this way. I was able to make payments from my own account in my app. Now every time I need to take new app key and can make payment only one time. Payments from other accounts (other pi network users) looks like can make payments as usual. 
Current situation is not good I can't test if payment flow is fine in my app every day. See image bellow. Refreshing app key every day is not fine.

![image](https://user-images.githubusercontent.com/41419745/211992882-54c03120-c50f-47aa-9601-18d7a3d7ea21.png)

**Comment by aurelienshz** [comment]
Hi,
To fix this error, you need to request the `payments` scope when authenticating the user, e.g:

```js
Pi.authenticate(["payments"], function onIncompletePaymentFound() { ... })
```
