### ISSUE TITLE
about KYC

### ISSUE THREAD

**Issue by Yichongtian** [pi-apps/pi-platform-docs#315]
My mother always asks me to carry out KYC verification on PI APP by taking photos with my ID card. I think this is dangerous behavior. Why do I need to do this?

**Comment by natey74** [comment]
verifiagion

**Comment by ahmeed38** [comment]
SCLWWBX76MYXWP4GXJ24UI5FZJOE2XPY5EB5EIZNZYUHHK7M3OLXTYCL
