### ISSUE TITLE
ECONOMIC Liberation of CLEANING Work/the C2E Pi Gold voucher project converts

### ISSUE THREAD

**Issue by dongyollkim** [pi-apps/pi-platform-docs#318]
The pi gold voucher project incentivizes people to clean by offering a conversion of their cleaning movements into a digital currency gold

**Comment by Trushar2110** [comment]
@CryptoGing 
@hklee93
 @aurelienshz 
@kokkalis 
@Pasniczy 
![Uploading Screenshot_20221114-161536_Twitter.jpg…]()

**Comment by dongyollkim** [comment]
For the development, for the first time  we need the time to improve. Thanks so much. Need feedback!
