### ISSUE TITLE
There is an issue when logins from an app to another

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#321]
There is an error when login from an app to another. Try login in one app1, then get accessToken, UID and username, pass it app1 backend, login with /me, then pass to another app2. In the app2 send to /me endpoint the authorization accessToken, it will logins, and that's an error.

Put this code in app2 in Python3 and receive the parameters (accessToken, uid, username) from app1. It will logins, even outside Pi apps, you can try run it in localhost, getting the accessToken, uid and username, from a server:

    import requests
    import json
    
    accessToken = ''
    uid = ''
    username = ''
    
    re = requests.get('https://api.minepi.com/v2/me', data={},json={},headers={'Authorization': "Bearer " + accessToken})
    print(str(re))
    
    try:
        result = re.json()
        result_dict = json.loads(str(json.dumps(result)))
    
        print(str(result_dict))
    
        if not (result_dict['uid'] == uid and result_dict['username'] == username):
            print("Authorization failed")
        else:
            print("Logged In")
    except:
        print("Authorization error")

In NodeJS you can do it also:

    const axios = require('axios');

    async function exec(accessToken) {
        const me = await axios.get('https://api.minepi.com/v2/me', {headers: {'Authorization': 'Bearer ' + accessToken}});
        console.log(me.data);
    }
    
    exec('123456');

It could cause other Pi App can login in my Pi App sending its own accessToken. I'm the App2, App1 will send his accessToken, and authenticate in my system, like Phishing.

My solution was to check uid validation against the user uid in my app database, plus /me endpoint validation.

For example, CoreTeam could implement the get of IP and DNS lookup comparisson, to check if the request comes from the Server registered at the Pi App. Or at least, create another method /me-login, to let check the accessToken by IP.

**Comment by rockcesar** [comment]
Ok, I realized the thing, there is no issue, /me is public. We have to compare with UID. Done.

**Comment by Okorie150** [comment]
Great job 👏

**Comment by Okorie150** [comment]
Good and amazing 👏 work 👏

**Comment by joshuarendora1** [comment]
Hi Good Day before we begin can i ask a little favor to Subscribe these
Youtube chanel?

Please click Link Below. 👇👇


https://youtube.com/shorts/va3bZK4wiKU?feature=share



YOU'RE SUBSCRIPTION IS REALLY A BIG HELP TO THE CHARITY WE CHOSEN TO
RECEIVED 75% OF THE SALLARY WE MAKE IN THE FUTURE.

WE ARE EXPECTING THAT YOU ARE ALSO IN LINE AND 1 OF THOSE PEOPLE ALSO WHO
SUPPORT WHAT WE MAKE AND PLAN IN THE FUTURE IN HELPING OTHERS ♥️♥️♥️

THANK YOU SO MUCH ♥️
