### ISSUE TITLE
Winnings 

### ISSUE THREAD

**Issue by ThePain813** [pi-apps/pi-platform-docs#326]
I need a further review of the metamask  transaction of winnings I had .I did not receive them and someone may had stolen them from me

**Comment by AZIMALAVI** [comment]
سلام .خوبید من هستم

در تاریخ جمعه ۲۴ فوریهٔ ۲۰۲۳،‏ ۰۷:۰۹ ThePain813 ***@***.***>
نوشت:

**Comment by ThePain813** [comment]
Why are I closing this without consulting me bubba, where my tokens?

**Comment by 0205miss** [comment]
This place isn't for you to ask this kind of question.
