### ISSUE TITLE
Building 

### ISSUE THREAD

**Issue by Dossiya2424** [pi-apps/pi-platform-docs#333]

**Comment by nanis94** [comment]
#333

**Comment by nanis94** [comment]
#333

**Comment by joshuarendora1** [comment]
Hi Good Day before we begin can i ask a little favor to Subscribe these
Youtube chanel?

Please click Link Below. 👇👇


https://youtube.com/shorts/va3bZK4wiKU?feature=share



YOU'RE SUBSCRIPTION IS REALLY A BIG HELP TO THE CHARITY WE CHOSEN TO
RECEIVED 75% OF THE SALLARY WE MAKE IN THE FUTURE.

WE ARE EXPECTING THAT YOU ARE ALSO IN LINE AND 1 OF THOSE PEOPLE ALSO WHO
SUPPORT WHAT WE MAKE AND PLAN IN THE FUTURE IN HELPING OTHERS ♥️♥️♥️

THANK YOU SO MUCH ♥️

**Comment by ajitt143** [comment]
Unable to reset the password of my Pi account. Can someone help?
