### ISSUE TITLE
How can I handle this situation?

### ISSUE THREAD

**Issue by SunSeekerX** [pi-apps/pi-platform-docs#336]
You already have a pending paymenton this app, which needs an actionfrom the developer. lf you're sure thatyou haven't already made this paymentplease try again ater.

I often encounter this kind of error that prevents development from continuing.

**Comment by pi-core-team** [comment]
This error is presented by the Pi SDK when there is a pending payment which has not been approved or completed by the developer. 

To handle this you need to setup the callback functions of the `onImcompletePaymentFound` method. This will handle the error by either completing or cancelling the payment. 

If you can confirm that you are properly handling this payment callback but still receiving the error then we can look further into this.

**Comment by Danbello33** [comment]
Please help me out am a developer I need a URL for my API and web 3 app how do I get it please
