### ISSUE TITLE
tlustymastodont

### ISSUE THREAD

**Issue by romanedwardtlusty123** [pi-apps/pi-platform-docs#356]
Hey, I just joined the Minego ecosystem. Join me and earn more. Use my referral code  https://minego.io/download?reference_username=tlustymastodont![1628354215745672.jpg](https://github.com/pi-apps/pi-platform-docs/assets/947861/e733d616-efd1-47b7-9409-c42cdc6e6ae1)

**Comment by Sahirsk** [comment]
Hi
