### ISSUE TITLE
500 error begin returned from /approve API endpoint. 

### ISSUE THREAD

**Issue by dannybutterfield1880** [pi-apps/pi-platform-docs#36]
I have created a second project as I cannot continue working on my first project until the pending project thing is sorted. Now when I try to call the /payments/paymentId/approve API its returning a 500 error 

[View code here](https://github.com/dannybutterfield1880/fire-pi-base/blob/main/functions/pi-network/services.js)

I'm doing the same thing as yesterday when the payment worked but I didn't complete it.

Is anyone else getting this error back from the /approve endpoint

**Comment by dannybutterfield1880** [comment]
Here is the output in my command line

<img width="923" alt="error" src="https://user-images.githubusercontent.com/62266392/124259385-5b2f5180-db26-11eb-93b2-093983bf6cd0.png">

A html 500 error page is returned from the pi API

<img width="761" alt="error1" src="https://user-images.githubusercontent.com/62266392/124259584-93cf2b00-db26-11eb-9cda-7a7441f3b16d.png">

**Comment by dannybutterfield1880** [comment]
I believe this duplicates #29

**Comment by dannybutterfield1880** [comment]
To confirm

<img width="928" alt="Screenshot 2021-07-02 112213" src="https://user-images.githubusercontent.com/62266392/124260631-cf1e2980-db27-11eb-9f2d-91935e29da5d.png">

**Comment by Sten435** [comment]
Same problem here, They really need a stable version of the API.

**Comment by dannybutterfield1880** [comment]
@Sten435 yep I'm completely stuck now

**Comment by Sten435** [comment]
The /approve end-point works put the /complete end-point does not.

**Comment by Sten435** [comment]
@dannybutterfield1880 Look this is the error i recive: (account not found) ![Screenshot_20210702-133859.jpg](https://user-images.githubusercontent.com/44066744/124269749-95571e00-db3b-11eb-80da-03e7910542e9.jpg)

**Comment by dannybutterfield1880** [comment]
I can't get either to work now, approve is also giving me a 500 error exactly the same as complete.

**Comment by dannybutterfield1880** [comment]
@Sten435 sorry that last statement I made is incorrect. I have just tested my code that worked yesterday with someone else's account and the approve endpoint does work correctly. My other co see e must be incorrect somewhere

**Comment by dannybutterfield1880** [comment]
Also this seems to be an error with my code
