### ISSUE TITLE
https://www.loom.com/share/8b2c826a362947689fab237bd1113db0?sid=59727d1b-88f3-4009-b57a-e3965dc4b11c

### ISSUE THREAD

**Issue by Bami1995** [pi-apps/pi-platform-docs#362]

**Comment by Maungmaunglwin096062** [comment]
Please help me how to make it best and easiest

**Comment by Mohamedelsaka1** [comment]
🙃🙄‬‫في 06‏/10‏/2023 الساعة 4:35 ص، كتب/كتبت ‏Bami1995 ***@***.***>:‬﻿

**Comment by TotalDH986** [comment]
What is this

**Comment by sharmanshiri** [comment]
> 

Sir do you have any wallet at all or you encounter with crypto transaction first time?
