### ISSUE TITLE
android  pi broswer session  is normal  ,ios pi browser session have a big problem ,Has anyone met it

### ISSUE THREAD

**Issue by SuperHax** [pi-apps/pi-platform-docs#37]

**Comment by Sten435** [comment]
Can you give us a detailed description about your problem

**Comment by SuperHax** [comment]
> Can you give us a detailed description about your problem

ok,just wiat ,i upload a video here

**Comment by SuperHax** [comment]
https://user-images.githubusercontent.com/12175390/124269000-e6333a80-db6c-11eb-803b-c84bc3a8b655.mp4

**Comment by SuperHax** [comment]
> Can you give us a detailed description about your probledi

> Can you give us a detailed description about your problem

differnet server,and differnet domain,314shop.cn is verify by developer.pi, gp.uppay0.com is not verify,but 314shop.cn can not get session ,and the gp.uppay0.com is ok, What is the reason。

**Comment by SuperHax** [comment]
> Can you give us a detailed description about your problem

and on android both two is normal

**Comment by Sten435** [comment]
Try reinstalling the application, it can be an error with caching. By reinstalling do you clear the cache.

**Comment by SuperHax** [comment]
> Try reinstalling the application, it can be an error with caching. By reinstalling do you clear the cache.

i use more than 10 new phone to test this

**Comment by SuperHax** [comment]
> Try reinstalling the application, it can be an error with caching. By reinstalling do you clear the cache.

and you can use your phone visit my website 314shop.cn, and you register a account to login

**Comment by dannybutterfield1880** [comment]
To clear the cache you can go to your phone settings, applications then select pi browser then storage clear cache

**Comment by dannybutterfield1880** [comment]
I cannot access the site. It will be because of UK internet laws. This is something I have noticed. Obviously a lot of Chinese, Malaysian and Indonesian people are build pi websites. This will mean anyone in the UK will not be able to access those websites, this could also effect other European countries and even USA. Which is a bit annoying.

**Comment by SuperHax** [comment]
> To clear the cache you can go to your phone settings, applications then select pi browser then storage clear cache

i already try this ,and i use more than 10 new iphone to test this

**Comment by SuperHax** [comment]
> I cannot access the site. It will be because of UK internet laws. This is something I have noticed. Obviously a lot of Chinese, Malaysian and Indonesian people are build pi websites. This will mean anyone in the UK will not be able to access those websites, this could also effect other European countries and even USA. Which is a big problem.



> I cannot access the site. It will be because of UK internet laws. This is something I have noticed. Obviously a lot of Chinese, Malaysian and Indonesian people are build pi websites. This will mean anyone in the UK will not be able to access those websites, this could also effect other European countries and even USA. Which is a big problem.

you can use vpn to visit my website

**Comment by dannybutterfield1880** [comment]
@SuperHax fair point 👍

**Comment by WK008HK0** [comment]
Is there a solution to this problem, please let me know, I have this problem too, I need help

**Comment by 0205miss** [comment]
According to Safari policy , third party app can't use cookie and this may cause the session get wrong
