### ISSUE TITLE
Все не как 

### ISSUE THREAD

**Issue by 1234567891011111112227** [pi-apps/pi-platform-docs#386]
https://api.testnet.minepi.com/accounts/GCOR3TJAYA4JDV6GJSREO4TRDUW32IA7BQN3IMY553HQ26NL77W7TEAM

**Comment by fetouh88** [comment]
Pi Network

في الأربعاء، ٢٠ مارس ٢٠٢٤ ٥:٥٣ م Grishanya ***@***.***> كتب:
