### ISSUE TITLE
Account not found to complete payment.

### ISSUE THREAD

**Issue by Sten435** [pi-apps/pi-platform-docs#39]
### When I want to complete a payment, I get an error that says "Account not found, Please check your passphrase again. A transaction was not submitted."

https://user-images.githubusercontent.com/44066744/124315374-23e79180-db74-11eb-8b45-43e955a1780c.mp4

![image](https://user-images.githubusercontent.com/44066744/124314122-319c1780-db72-11eb-8cc2-c46973bcc323.png)

I tried reinstalling the pi-browser but I get the same results...
I also have this error on other people's applications.

Greetings
Stan P

**Comment by dannybutterfield1880** [comment]
What do you get if you output the response of Pi.authenticate() as it seems like you are getting passed that call.

**Comment by Sten435** [comment]
@dannybutterfield1880 
I get this (i cut some sensitive info out)

![Screenshot_20210702-213515.jpg](https://user-images.githubusercontent.com/44066744/124321161-82653d80-db7d-11eb-964b-0aa62f47b395.jpg) 

But i get this error also, and i don't know what it means...

![Screenshot_20210702-213453.jpg](https://user-images.githubusercontent.com/44066744/124321205-9a3cc180-db7d-11eb-9dfc-c9dd852f013c.jpg)

**Comment by dannybutterfield1880** [comment]
Make sure you are passing the txid to the body of the /complete request

**Comment by dannybutterfield1880** [comment]
<img width="449" alt="complete post" src="https://user-images.githubusercontent.com/62266392/124321970-817cdd80-db76-11eb-8e17-e38c1ee30d33.png">

This is my /complete post request using axios. You can install that using `npm i --save axios` then import it at the top of the javascript file using `import axios from 'axios'`

**Comment by dannybutterfield1880** [comment]
I'm guessing you solved this issue?

**Comment by Sten435** [comment]
Does not resolve the issue.

**Comment by B-Derouet** [comment]
@Sten435 are you using a rooted/jailbroken phone? I installed a custom OS on my phone, have the same error and a CT dev told me that the transaction system with the SDK doesn't work with rooted/jailbroken phones.

**Comment by dannybutterfield1880** [comment]
@B-Derouet I am using it on a rooted device and not having any problems at all

**Comment by B-Derouet** [comment]
@dannybutterfield1880 I didn't rooted my device either, just changed the OS. One thing that bothers me is that on Pi Browser, it doesn't ask for my wallet passphrase (and it doesn't work), but on a browser on my computer, it does ask me for my wallet passphrase and the payment works...

**Comment by dannybutterfield1880** [comment]
@B-Derouet is that an issue you are having with all pi apps? I'm not having an issue in the pi browser, it asks me for my wallet address and everything is fine. Also, how do you get it working in a normal browser?

**Comment by B-Derouet** [comment]
@dannybutterfield1880 ok, I reset my wallet and now it's working. Don't know how or why... And for normal browser, this is very tricky...

**Comment by dannybutterfield1880** [comment]
@B-Derouet Take a look at this repo for when you are using a normal browser https://github.com/gradosevic/pi-mock it's just mocks the responses from the pi SDK then when you come to the pi browser it will work perfectly also I found you can check for the pi browser by using 

`
navigator.userAgent.includes('PiBrowser')

`

**Comment by dannybutterfield1880** [comment]
@Sten435 I got this error when I wasn't passing the txid to the body of the POST request to /complete

**Comment by Sten435** [comment]
Im not using a rooted device.

**Comment by Sten435** [comment]
> @dannybutterfield1880 ok, I reset my wallet and now it's working. Don't know how or why... And for normal browser, this is very tricky...

How did you reset it?

**Comment by B-Derouet** [comment]
@Sten435 in Pi Wallet, I just created another wallet.

**Comment by Sten435** [comment]
@B-Derouet @dannybutterfield1880 
Thanks, resetting my wallet fixed the error!

**Comment by dannybutterfield1880** [comment]
@Sten435  awesome! 👍
