### ISSUE TITLE
onIncompletePaymentFound is called with payments with no txid / blockchain transaction

### ISSUE THREAD

**Issue by Sten435** [pi-apps/pi-platform-docs#40]
The documentation says that if you activated the function onIncompletePaymentFound() a PaymentDTO type must be given a response. The response should then also contain a _**txid**_ , but it does not as you can see in the picture below.

I thought that the function onIncompletePaymentFound() would return a _**txid**_ because it is written on the documentation.

Normally you should get this back: 
```

  identifier: string, 
  user_uid: string, 
  amount: number, 
  memo: string, 
  metadata: Object,
  to_address: string,
  created_at: string, 
  
  status: {
    developer_approved: boolean,
    transaction_verified: boolean,
    developer_completed: boolean,
    cancelled: boolean,
    user_cancelled: boolean,
  },
  
  transaction: null
    txid: string,
    verified: boolean
    _link: string,
  },
```

BUT you get this back

```
  identifier: string,
  user_uid: string,
  amount: number, 
  memo: string, 
  metadata: object,uik
  to_address: string,
  created_at: string, 
  
  status: {
    developer_approved: boolean, 
    transaction_verified: boolean, 
    developer_completed: boolean, 
    cancelled: boolean,
    user_cancelled: boolean,
    transaction: null
  }
```

![err](https://user-images.githubusercontent.com/44066744/124332502-e2fe7580-db91-11eb-9fc5-69873d8b95c4.png)

**Comment by dannybutterfield1880** [comment]
You can use the get payment API endpoint to load the payment by the identifier if needed this will return a PaymentDTO

**Comment by Sten435** [comment]
@dannybutterfield1880 Can I chat with you on discord, I have some questions...

StanKoffieMan#1772

**Comment by dannybutterfield1880** [comment]
@Sten435 of cause you can

**Comment by Sten435** [comment]
> @Sten435 of course you can

Would you add me on discord?
StanKoffieMan#1772

**Comment by dannybutterfield1880** [comment]
@Sten435 done

**Comment by B-Derouet** [comment]
This is normal. In fact, if there is a pending/incomplete payment, it means that the transaction didn't take place, so there is no transaction id for a non-existent transaction, that's why the transaction property of the returned PaymentDTO is null.

**Comment by Sten435** [comment]
But i need it to call /complete? To finish the ongoing payment?

**Comment by B-Derouet** [comment]
@Sten435 Currently, you can't do anything with a pending payment that has no transaction. I hope that the Core Team will provide a solution to continue or cancel a payment using its identifier.

**Comment by dannybutterfield1880** [comment]
@Sten435 at the moment there is no way to continue a payment that has not been approved. You will need to call createPayment again to get into the payment flow. You can manually complete a payment but not approve

**Comment by aurelienshz** [comment]
> @Sten435 Currently, you can't do anything with a pending payment that has no transaction. I hope that the Core Team will provide a solution to continue or cancel a payment using its identifier.

Yup, that's a confirmed bug on our side. `onIncompletePaymentFound` should NOT be called with a payment for which the user has not made any blockchain transaction. We have a fix on the way, I'll post updates here when it's deployed. Apologies for the inconvenience this caused.

**Comment by aurelienshz** [comment]
Hi! The fix has been deployed yesterday (CEST) on our backend servers. I think the bug is no longer occurring on our end. Let me know if you're still experiencing an issue with onIncompletePaymentFound. In the meanwhile, I'll close this issue. Feel free to reopen it if you're still encountering the bug.

**Comment by roghayehkharazmi** [comment]
salehkharazmi

**Comment by roghayehkharazmi** [comment]
hello

**Comment by roghayehkharazmi** [comment]
🖐

**Comment by lazike66** [comment]
Nice
