### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by vcyk** [pi-apps/pi-platform-docs#44]
This is not an issue per se but a much needed functionality.  Quite frequently an application would need to refund partial or full amount to the user ie the payer for many business reasons.  Would this be provided in the SDK and API ?  @aurelienshz 
Thinking aloud could this be a negative amount in the Pi.createPayment call ?

**Comment by dannybutterfield1880** [comment]
@vcyk good shout!

**Comment by Madhurmila44** [comment]
Thank you sir

**Comment by Sten435** [comment]
I agree.

**Comment by B-Derouet** [comment]
Currently, if you really want to have this functionality in your application directly (without waiting for a simpler solution via the Pi Network API v2), there is a workaround, but you would have to create your own API on a server (you can do it directly on the frontend, but the script requires a mnemonic that should not be shared in any way). Here is how you could do it:

- Let's take for example a server that has the address https://my-app.com/, you could, with a routing system, add a POST request processing system to the address https://my-app.com/refund that would ask as a request body this JSON code:
```json
{
  "txid": "the id of the transaction to be refunded",
}
```
- The POST request processing system to the address https://my-app.com/refund could trigger the `refund` function of this code to perform the transaction:
```js
import StellarSdk from 'stellar-sdk';
import bip39 from 'bip39';
import { derivePath } from '@hawkingnetwork/ed25519-hd-key-rn';
import axios from 'axios';

const testnetApiEndpoint = 'https://api.testnet.minepi.com/';
const server = new StellarSdk.Server(testnetApiEndpoint);

async function refund(transactionId) {
  const applicationPrivateKey = await getApplicationPrivateKey();
  const applicationAccount = await server.loadAccount(applicationPrivateKey.publicKey());
  const buyerPublicKey = await getBuyerPublicKey(transactionId);
  const transactionAmount = await getTransactionAmount(transactionId);
  const refundTransaction = new StellarSdk.TransactionBuilder(applicationAccount, {
    fee: await server.fetchBaseFee(),
    networkPassphrase: 'Pi Testnet',
  })
    .addOperation(
      StellarSdk.Operation.payment({
        destination: buyerPublicKey,
        asset: StellarSdk.Asset.native(),
        amount: transactionAmount,
      }),
    )
    .addMemo(StellarSdk.Memo.text('my-app refund'))
    .setTimeout(180)
    .build();

  refundTransaction.sign(applicationPrivateKey);

  await server.submitTransaction(refundTransaction);
}

async function getBuyerPublicKey(transactionId) {
  const response = await axios.get(`${testnetApiEndpoint}/transactions/${transactionId}`);

  return response.data.source_account;
}

async function getApplicationPrivateKey() {
  const seed = await bip39.mnemonicToSeed(process.env.mnemonic); // environment variable for the mnemonic of your application
  const derivedSeed = derivePath("m/44'/314159'/0'", seed); //derivation path of Pi Network mnemonic

  return StellarSdk.Keypair.fromRawEd25519Seed(derivedSeed.key);
}

async function getTransactionAmount(transactionId) {
  const response = await axios.get(`${testnetApiEndpoint}/transactions/${transactionId}/operations`);
  const transactionOperation = response.data.transactionOperations._embedded.records[0];

  return transactionOperation.amount;
}
```

I think something like this could work (adding error handling and adjusting a few things), but I would advise waiting for a better, simpler solution from the Core Team with the API.

**Comment by aurelienshz** [comment]
Hi there! Thanks @B-Derouet for providing this answer. It is indeed possible to directly make requests to the Testnet Blockchain API (api.testnet.minepi.com) using your private key (/passphrase) to make transactions if you need to refund a user.

In the future, we might expose a higher-level abstraction to developers to make this kind of task easier. However, remember that we do not store the wallet's private key of any user (as a matter of fact, it's never sent to our servers - it only exists on your phone, and that's why we ask you to keep a safe copy of the mnemonic).

This means we could not revert a payment without the developer of the app signing the refund transaction with their own private key, in a place where they control confidentiality of their private key. Indeed, it could make sense to provide APIs and/or server-side SDKs to make this process easier. Stay tuned!

**Comment by aurelienshz** [comment]
I'll close this for now, given that an answer has been provided. Feel free to update / reopen the issue if you have further questions.

**Comment by perfect-angle** [comment]
@aurelienshz Any update on this ? is there any direct api to refund or transfer?

**Comment by Ajmorris86** [comment]
#
[Submit_Elections_Confirmation.xlsx](https://github.com/pi-apps/pi-platform-docs/files/9788417/Submit_Elections_Confirmation.xlsx)

**Comment by perfect-angle** [comment]
@Ajmorris86  what is meaning of this xlsx file ?

**Comment by perfect-angle** [comment]
Can we send PI directly to public wallet ID account ?

**Comment by rockcesar** [comment]
Is there an example for Python?.

**Comment by rockcesar** [comment]
What I worry the most is the source of the code, I don't want to give my Mnemonic to any source. Only official. I trust in Pi Core Team.

**Comment by rockcesar** [comment]
# Following these steps:

https://developers.stellar.org/docs/tutorials/send-and-receive-payments

# And these:

https://github.com/pi-apps/pi-platform-docs/issues/44

# In Python:

from stellar_sdk import Asset, Keypair, Network, Server, TransactionBuilder
from stellar_sdk.exceptions import NotFoundError, BadResponseError, BadRequestError

server = Server("https://api.testnet.minepi.com")
source_key = Keypair.from_mnemonic_phrase("")
destination_id = ""
total_amount = "10"
network_passphrase = "Pi Testnet"

# The thing here is that from_mnemonic_phrase isn't retrieving the correct public_key.

print(source_key.public_key)

source_account = server.load_account(source_key.public_key)

# I have this error:

stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}

**Comment by hassanjimoh592-crypto** [comment]
I make a transferred for you scam account  name:Paul Uyinigwung 
Acct number: 6975386226
 Nombank Microfinance Bank
I transfer some of 58,261 naira. 
Please I want the money should be fun back to my account I transfer the money around 12:00 to 1:00 a.m today this morning please I want the money should refund back to my account

![Image](https://github.com/user-attachments/assets/81f96e04-bac3-4e26-81a9-33c5c67c0b63)
