### ISSUE TITLE
إنشاء FUNDING.yml

### ISSUE THREAD

**Issue by Ze0ro99** [pi-apps/pi-platform-docs#458]
https://github.com/Ze0ro99/MetaConnect/commit/f072d6d6d750d74949c36f3a8e81c414f9b14153

**Comment by Ze0ro99** [comment]
@KOSASIH

**Comment by Ze0ro99** [comment]
Can you contribute to the implementation of the project?

**Comment by KOSASIH** [comment]
Yes,  sure.  I can help your project.

**Comment by Ze0ro99** [comment]
Thank you sir, you have put most of the details My experience in the field is simple and PI motivated me to do this and achieve the dream. Thank you, how proud I am now.
