### ISSUE TITLE
Current version of documentation doesn't explain how to get user_uid after authenticates

### ISSUE THREAD

**Issue by aarrtturas** [pi-apps/pi-platform-docs#46]
Please provide details how to get user_uid after he/she authenticates. Can we get UserDTO after he authenticates?

Pi.authenticate(scopes, onIncompletePaymentFound).then(function(auth) {
  console.log(`Hi there! You're ready to make payments!`);
}).catch(function(error) {
  console.error(error);
});

**Comment by B-Derouet** [comment]
This is explained indirectly (although quite directly in reality) when we look at the AuthResult type and the signature of the authenticate() method [here](https://github.com/pi-apps/pi-platform-docs/blob/master/SDK_reference.md#authentication). You can get the user UID like this:

```js
Pi.authenticate(scopes, onIncompletePaymentFound).then(auth => {
  const userUid = auth.user.uid;
  // ...
})
```

**Comment by browolf** [comment]
is the User id a sequential number?  like the newest user has the highest number.

**Comment by B-Derouet** [comment]
@browolf No, it's a string identifier with numbers and letters.

**Comment by Sten435** [comment]
If anyone has questions about the Pi Network SDK or other general coding questions regarding anything related to the Pi Network, then you ask them in the Pi Network Developer Portal: **[](https://discord.gg/qM3fXPq4fK)**
It is a faster way to connect with people, instead of contact people through email, or through the Pi chat app, which can be a real pain.

This is not an AD, this is an informative post for people who may need a communication server for a question.

**Comment by wrramerson** [comment]
não consigo incorporar pi sdk em meu dapp

**Comment by Ossasis24Knice** [comment]
Can someone tell me how to figure this out

**Comment by popyelove** [comment]
this is just front js sdk, but how get the user info from backet by api? there is now doc to explain that.

**Comment by 0292568684** [comment]
So good

**Comment by CryptoGing** [comment]
To get the uid from the API you must first get the Access Token from the pi.Authenticate() call of the Pi SDK. Once you have that Access Token you pass it to your backend. From your backend you can call the `/me` endpoint of the Pi API passing the Access Token as a Bearer Token. That API call will return the uid and username

**Comment by SHADYKIMBUM** [comment]
S

**Comment by Minthu34** [comment]
?

**Comment by ThePain813** [comment]
Someone tell me what a whitelist is
