### ISSUE TITLE
Change the name shown in the app details / scopes popup in the Pi Browser

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#47]
Can I change the code name of my app?.

I want to change the code name of mi app in Pi Browser. I guess the name comes from this tag:

&lt;meta name="application-name" content="Platform"/&gt;

But I change it, and nothing. Example: the code name of wallet is wallet.pi.

**Comment by aurelienshz** [comment]
I'm not sure what you'd like to change here. Is it the domain name (the string that appears in the Pi Browser's address bar - "brainstorm.pi" in the screenshot below)? Or is it the name that appears in the gray bar on top of your app ("Brainstorm" in the screenshot below)?

![IMG_0251](https://user-images.githubusercontent.com/14823737/124572304-d8213a80-de48-11eb-83de-4b3864a5dbbf.jpg)

The name can 

You can change to a different domain name after deploying your app on the new domain, by updating the app on the developer portal accordingly. You'll have to go through the ownership verification for the new domain name. FYI, it is not possible for third-party developers to get .pi domain names at the moment.

**Comment by rockcesar** [comment]
The codename:

![pi_codename](https://user-images.githubusercontent.com/5984401/124584209-fc1d5580-de21-11eb-83b4-4209a29cd0de.jpeg)

**Comment by rockcesar** [comment]
@aurelienshz Ok, thanks for the answer. I'll have to wait until my app is added to Mainscreen.

**Comment by hklee93** [comment]
I believe the name you're pointing above is what you register on the dev portal?

**Comment by rockcesar** [comment]
Yes, I register different sites, that is one of them. The sites I registered were:

https://latin-chain.com
https://snake.latin-chain.com
https://sudoku.latin-chain.com
https://chess.latin-chain.com
https://piapp-example.latin-chain.com

**Comment by hklee93** [comment]
I just checked and in fact I was actually wrong. Sorry about the confusion. I'll see if we can let users update that name.

**Comment by rockcesar** [comment]
Ok, thank you!.

**Comment by tonytruong2009** [comment]
Dir @aurelienshz 

can you explain for me about pi://welcome.pi in Pi Browser?

**Comment by tzaddizidd** [comment]
yes , this is the prior lunching PI crypto coins

**Comment by mooha12** [comment]
minepi.com/mooha120

**Comment by Jejgodtime** [comment]
@aurelienshz

**Comment by Jejgodtime** [comment]
@tonytruong2009

**Comment by Jejgodtime** [comment]
@rockcesar

**Comment by Jejgodtime** [comment]
@tzaddizidd

**Comment by Jejgodtime** [comment]
@hklee93

**Comment by Shahidul783** [comment]
Shahidul783

**Comment by aurelienshz** [comment]
A fix has been deployed for this issue. The app details & scopes popup should now show the public user-facing name of your app, as set in the developer portal, instead of the machine-facing string which it used to be displaying.
