### ISSUE TITLE
Error messages when signing in with Google Auth

### ISSUE THREAD

**Issue by mitjans** [pi-apps/pi-platform-docs#49]
I have noticed that Pi SDK somehow captures sent messages and logs them in the console. Something like this:

`Received message with non-string data: {type: "webpackOk", data: undefined}`

I tried to add the "Login with Google" functionality to my app today, and I suddently saw a lot of errors:

```
pi-sdk.js:1 Native messaging: error when handling incoming message (possible response?). Error is logged below.

pi-sdk.js:1 SyntaxError: Unexpected token ! in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handleIncomingMessage (pi-sdk.js:1)
    at pi-sdk.js:1

pi-sdk.js:1 !_{"h":"I0_1625585678994"}
```

I am not sure, but I think this has to do with the messages captured and logged by the Pi SDK. Why are those messages being logged? Is it possible to fix this errors?

Thank you

**Comment by Sten435** [comment]
Im not sure but i think this is a issue in your code, becuse if i go to a website with a social login in the pi browser and click sign in with google than it works fine for me.

**Comment by mitjans** [comment]
I tried to sign in with google in multiple apps and the same message in issue #50 appears. This logs appear on the console when I try my app on a normal browser.

**Comment by Sten435** [comment]
Hmm, strange maybe @aurelienshz knows more about this...

**Comment by hklee93** [comment]
Hi, it just means the message isn't relevant to Pi SDK. You can ignore the error message.
