### ISSUE TITLE
Disallowed UserAgent when signing in with Google Auth

### ISSUE THREAD

**Issue by mitjans** [pi-apps/pi-platform-docs#50]
When I try to sign in using Google Auth SDK through Pi Browser, I get the following error:

```
Error 403: disallowed_useragent
```

**Comment by dannybutterfield1880** [comment]
You don't need to sign-in in your app. When the user is inside the pi browser they are authenticated through pi. When you call the Pi.authenticate() function it will give you the user's username. From this you could create a users table that is identifiable by the username therefore you could extend user data if you need too.
