### ISSUE TITLE
Payment window closed JavaScript event

### ISSUE THREAD

**Issue by dannybutterfield1880** [pi-apps/pi-platform-docs#51]
Hey guys, does anyone know if the payment window sends a JavaScript event I can catch so I can do some stuff once the user has successfully competed the payment and goes back to the website? 

Basically my cart is cleared via a Ajax call so when the user closes the pi payment flow the cart is still populated until the user refreshes so I just want to force a refresh but can't seem to do it in onReadyForServerCompletion

**Comment by B-Derouet** [comment]
@dannybutterfield1880 You can indeed detect the closing of the payment page (the return of the user to your site) with this piece of code:

```js
window.addEventListener("message", (message) => {
    const data = JSON.parse(message.data);
    
    if (data.type !== "@pi:messaging:endSuperposeDisplayUrl") {
        return;
    }
    
    // the things you want to do when the superposed page is closed
})```

But be careful, it detects any closure of the superposed page (like the payment one), you'll have to check afterwards if the payment has been made successfully!

**Comment by dannybutterfield1880** [comment]
@B-Derouet thanks for this that is perfect!

**Comment by dannybutterfield1880** [comment]
@B-Derouet I don't seem to be receiving a message with that type

![image](https://user-images.githubusercontent.com/62266392/124910577-a98b9700-dfe3-11eb-8ce9-c7394b2b4a34.png)

This whole output of my payment flow. As you can see I get `@pi:app:payments:start_payment_flow` and `@pi:app:payments:wait_for_transaction` but then nothing after that. I am getting no messages with a type when the superpose payment window ends

**Comment by B-Derouet** [comment]
It's normal, this message isn't log in the terminal, do you have a message if you do this?

```js
window.addEventListener('message', (message) => {
    let data;
    
    try {
        data = JSON.parse(message.data);
    } catch {
        return;
    }
    
    if (data?.type !== '@pi:messaging:endSuperposeDisplayUrl') {
        return;
    }
    
    console.log('close superposed page:', data);
})
```

**Comment by dannybutterfield1880** [comment]
@B-Derouet no that console.log did not output the last log I can see is developerCompleted: true the same as the screenshot above

**Comment by dannybutterfield1880** [comment]
@aurelienshz is this a known bug?

**Comment by bambangSiS** [comment]
pi-sdk.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://sandbox.minepi.com') does not match the recipient window's origin ('https://mywebsite.com').

i got some error like this.
can any one help me
