### ISSUE TITLE
Error!  You already have a pending payment on this app, which needs an action from the developer.lf you're sure that you haven'talready made this payment, please try again later.

### ISSUE THREAD

**Issue by liqj123** [pi-apps/pi-platform-docs#52]
I have been able to place a normal order and pay successfully in PI browser. After an error was reported in a transaction last night, I could not continue the next transaction. I repeatedly prompted the following error, and I detected it and couldn't solve it. Now the situation is that my PI account can no longer place an order. Every time, the following prompt pops up to remind me that there is an order that has not been processed, but I have detected it and can't solve it. I need the project party to solve this   @aurelienshz @kokkalis 

**Error!
You already have a pending
payment on this app, which needs an action from the developer.lf
you're sure that you haven'talready made this payment, please try again later.**

**Comment by liqj123** [comment]
My PI payment error reporting process is as follows: input the website address, place an order normally, wake up PI payment, and when I arrive at the waiting countdown interface, the page prompts that an error has been reported, but PI has been deducted from my wallet, and the order has not been completed, Then I go to the next transaction, and the pi system will repeatedly prompt and report an error, which means that this transaction must be solved before the next transaction can be continued, but I can't solve it. I need the guidance of the project party to solve it.

**Comment by dannybutterfield1880** [comment]
@liqj123 Hey this is because the payment has been approved but not completed. Do you have access to debugging in the application? The best way to solve this would be to look for

`function onIncompletePaymentFound(payment) { /* ... */ };`

here you could console.log(payment) this will include the identifier (paymentId) and the txid (transaction id). You would then need to manually make a POST call to `https://api.minepi.com/v2/payments/{paymentId}/complete` with a body `{"txid": "YOUR_TXID_HERE"}` with the headers `{"Authorization": "Key YOUR_API_KEY_HERE"}` I used postman to do this.

For debugging you can use ADB and chrome usb debugging

**Comment by liqj123** [comment]
> @liqj123嘿，这是因为付款已被批准但尚未完成。您是否有权在应用程序中进行调试？解决这个问题的最好方法是寻找
> 
> `function onIncompletePaymentFound(payment) { /* ... */ };`
> 
> 在这里，您可以`console.log(payment)`将包括标识符 (paymentId) 和 txid（交易 ID）。然后，您需要使用带有我使用邮递员执行此操作的标题`https://api.minepi.com/v2/payments/{paymentId}/complete`的正文手动进行 POST 调用。`{"txid": "YOUR_TXID_HERE"}``{"Authorization": "Key YOUR_API_KEY_HERE"}`
> 
> 对于调试，您可以使用 ADB 和 chrome usb 调试

Thank you, I'm worth the test. At the same time, what method can I use to debug IOS mobile phone?

**Comment by dannybutterfield1880** [comment]
This is because @liqj123 I'm not sure about ios personally sorry

**Comment by Sten435** [comment]
I have this issue to
![Screenshot_20210715-213452.jpg](https://user-images.githubusercontent.com/44066744/125847527-44283838-8974-474d-b851-78b7c33c367c.jpg)

**Comment by liqj123** [comment]
> 我有这个问题
> ![截图_20210715-213452.jpg](https://user-images.githubusercontent.com/44066744/125847527-44283838-8974-474d-b851-78b7c33c367c.jpg)

 Have you solved the card order problem? I haven't solved it yet. It's still in card status

**Comment by Sten435** [comment]
Yes, I solved it, you have to complete the payment from the `onIncompletePaymentFound(payment)` function !
 I dit it like this;

```javascript
 async function onIncompletePaymentFound(payment) {
        let paymentId = payment.identifier
        let txid = payment.transaction.txid

await axios.post(`https://api.minepi.com/v2/payments/${paymentId}/complete`, { txid }, {
            headers: {
                'Authorization': `Key YOURAPPIKEY`
            }
        })
    };
```
