### ISSUE TITLE
Inconsistent timestamps 

### ISSUE THREAD

**Issue by dannybutterfield1880** [pi-apps/pi-platform-docs#53]
I have just noticed that the timestamps in wallet.pi are not consistent.

![IMG_20210708_103946.jpg](https://user-images.githubusercontent.com/62266392/124900360-e56d2f00-dfd8-11eb-8647-722ffeb72e8e.jpg)

![IMG_20210708_104002.jpg](https://user-images.githubusercontent.com/62266392/124900388-eb631000-dfd8-11eb-93bb-b9ee897a2a28.jpg)

As you can see the timestamp on the payment history screen is my correct timezone (GMT) however the timezone when I click into the payment is UTC which makes the times an hour out.

**Comment by Sten435** [comment]
Yea, just checked and i have this to...
![Screenshot_20210708-122853.jpg](https://user-images.githubusercontent.com/44066744/124907118-14d76800-dfe8-11eb-97e8-236b94141c1e.jpg)

**Comment by B-Derouet** [comment]
Personally, I don't see any problem with the timestamp, the pop-up shows the information of the transaction and it's well specified that it's the UTC time (the time recorded in the blockchain, thus the time to be used in case of research).

**Comment by dannybutterfield1880** [comment]
@B-Derouet if it's not recognised as a bug I'm happy to close the issue

**Comment by Sten435** [comment]
Good point @B-Derouet .

**Comment by hklee93** [comment]
There are certain places where date is being displayed. I'll put this into our backlog and revisit later. Thanks for reporting this 🙂
