### ISSUE TITLE
Intercommunication between apps

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#54]
When I redirect with location.href in JavaScript, from the domain app-domain1.com to the domain app-domain2.com, and both are registered domains in developer.pi, the functionalities of app-domain2.com, for payments, don't work.

**Comment by Sten435** [comment]
Are you sure the code of domain2 is correct?

Does that code from domain2 work on domain1

Maybe try that bud, I hope it helps... ;-)

**Comment by rockcesar** [comment]
I have two domains, both are working well in separates apps, both are making payments in each domain, but I can't do location.href from a domain to another, the API doesn't works.

@Sten435 if you have two working apps, try that situation. Not working.

**Comment by rockcesar** [comment]
the location.href should be from a working domain app, to another working domain app.

**Comment by rockcesar** [comment]
It doesn't has to be with the domain, it's about that the Pi Browser loads some variables to the app, and if you access an app, from another app, the variables aren't charged.

**Comment by Muchumacbd039** [comment]
I support this idea.Keep PI live

**Comment by lazike66** [comment]
Best
