### ISSUE TITLE
pi-network-error:  Error: Pi Network SDK was not initialized. Call init() before any other method.

### ISSUE THREAD

**Issue by dannybutterfield1880** [pi-apps/pi-platform-docs#6]
pi-network-error:  Error: Pi Network SDK was not initialized. Call init() before any other method. 

I have loaded the pi-sdk into my index.html and can access window.Pi but then when I try to call Pi.authenticate() I get the above error. Then when I call Pi.init() I get the error: "TypeError: Cannot read property 'version' of undefined".

**Comment by mitjans** [comment]
Check out this [issue](https://github.com/pi-apps/pi-platform-docs/issues/2).

**Comment by mariaica55mi** [comment]
Salut!

**Comment by dannybutterfield1880** [comment]
Thank you!
