### ISSUE TITLE
403 Forbidden error when user cancel a payment

### ISSUE THREAD

**Issue by B-Derouet** [pi-apps/pi-platform-docs#67]
When we click on the `cancel` button on the payment window, the request to `https://socialchain.app/v2/payments/{payment_id}/cancel` returns a 403 Forbidden error, so we can't cancel a payment and the payment window won't close.

**Comment by vidaniello** [comment]
I've just test in production mode with my app and canceling the transaction work well. Try to my app, copy and paste in pi browser this link: donatepi.glitch.me

**Comment by Sten435** [comment]
@vidaniello is right the `CANCEL` button does `NOT` work if you're using the `SANDBOX` but when you're in `PRODUCTION` mode the issue is `RESOLVED`.

I tried `CANCELING` the payment with Postman and that works. But in the `SANDBOX ENVIREMENT`, the cancel button does `NOT` work.

**Comment by B-Derouet** [comment]
Quite strange, when I test on demo.pi with the Pi Browser application, it works, but with the same application on my computer (in production mode), it doesn't work.

**Comment by hklee93** [comment]
Will look into this very soon. Thanks for reporting!

**Comment by hklee93** [comment]
I believe this is now fixed. Let me know if it still happens.

**Comment by B-Derouet** [comment]
Perfect, thank you!
