### ISSUE TITLE
Web app has updated and every browser can see the new version but pi browser still in old version

### ISSUE THREAD

**Issue by aszasz1234** [pi-apps/pi-platform-docs#69]
Just like title, my web has updated and it is update in google chrome but when I use pi browser, it still in old version

**Comment by Sten435** [comment]
You have to reinstall the app on your phone, or clear your cache.

**Comment by vidaniello** [comment]
Can you log server side?? If you can, assert that when pi browser pointing to your page, the server respond with updated page.

**Comment by Sten435** [comment]
Are you using the sandbox mode ?

When you want to use your application in the Pi browser you need to make sure the sandbox bool is set to `FALSE`

```
Pi.init({ version: "2.0", sandbox: false })
```

**Comment by rockcesar** [comment]
It is happening in other phones, it's a general issue. You need to clear cache by now.
