### ISSUE TITLE
Where Can I get Server API Key authorization

### ISSUE THREAD

**Issue by eastmaels** [pi-apps/pi-platform-docs#70]
I'm trying to approve a payment using this:

https://github.com/pi-apps/pi-platform-docs/blob/master/platform_API.md#approve-a-payment

However, it returns a `'This endpoint requires either a Server API Key or Access Token authorization.'` error.

Where can I get my Server API key authorization?

**Comment by aszasz1234** [comment]
Server API key can get in develop.pi , and you should post a message to  [api.minepi.com/v2/payments/{payment_id}/approve]
{payment_id} will get by the callback function and
the header must contain [Authorization: Key <your Server API Key>]

**Comment by aszasz1234** [comment]
> > Server API key can get in develop.pi , and you should post a message to [api.minepi.com/v2/payments/{payment_id}/approve]
> 
> > {payment_id} will get by the callback function and
> 
> > the header must contain [Authorization: Key ]
> 
> 
> 
> Thank you for your reply. I did that but the result was the same. What library do you use to send post requeststo api.minepi.com? I use axios and did it like this:
> 
> 
> 
> ```javascript
> 
>     let { payment_id } = req.body;
> 
>     const data = {
> 
>       todo: 'Buy the milk'
> 
>     };
> 
>     const headers = {
> 
>       'Authorization': process.env.API_KEY
> 
>     };
> 
>     axios
> 
>       .post(`https://api.minepi.com/v2/payments/${payment_id}/approve`, data, headers)
> 
>       .then(res => {
> 
>         console.log(`statusCode: ${res.statusCode}`)
> 
>         console.log(res)
> 
>       })
> 
>       .catch(error => {
> 
>         console.error(error)
> 
>       })
> 
> ```

Authorization: Key APIKey
You should add a Key before your api key

**Comment by vidaniello** [comment]
> > Server API key can get in develop.pi , and you should post a message to [api.minepi.com/v2/payments/{payment_id}/approve]
> > {payment_id} will get by the callback function and
> > the header must contain [Authorization: Key ]
> 
> Thank you for your reply. I did that but the result was the same. What library do you use to send post requeststo api.minepi.com? I use axios and did it like this:
> 
> ```js
>     let { payment_id } = req.body;
>     const data = {
>       todo: 'Buy the milk'
>     };
>     const headers = {
>       'Authorization': process.env.API_KEY
>     };
>     axios
>       .post(`https://api.minepi.com/v2/payments/${payment_id}/approve`, data, headers)
>       .then(res => {
>         console.log(`statusCode: ${res.statusCode}`)
>         console.log(res)
>       })
>       .catch(error => {
>         console.error(error)
>       })
> ```

append ''KEY" here

    ....
        const headers = {
       'Authorization': "KEY "+process.env.API_KEY
     };

**Comment by eastmaels** [comment]
Thanks for the tips. I updated my codes as per [this reference](https://blog.logrocket.com/how-to-make-http-requests-like-a-pro-with-axios/#customheaders).

```javascript
    const data = {
      todo: 'Buy the milk'
    };
    const options = {
      headers: { 'Authorization': "Key " + process.env.API_KEY }
    };
    axios
      .post(`https://api.minepi.com/v2/payments/${payment_id}/approve`, data, options)
      .then(res => {
        console.log(`statusCode: ${res.statusCode}`)
        console.log(res)
      })
      .catch(error => {
        console.error(error)
      })
```
