### ISSUE TITLE
Request payment info, got error 500

### ISSUE THREAD

**Issue by vidaniello** [pi-apps/pi-platform-docs#71]
Request payment info, example:

     api.minepi.com/v2/payments/{txid}

pi endpoint respond with code 500 

    <!DOCTYPE html>
    <html>

    <head>
        <title>We're sorry, but something went wrong (500)</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <style>
    .......

I've put in GET request, the server API key:
 
    Authorization: Key XXXXXXXXXXXXXXXXXXXXXXX

**Comment by vidaniello** [comment]
I say it another way: I need to access at the transaction as a PaymentDTO object, because I have to read the `metadata` and `memo` fields...

**Comment by Sten435** [comment]
You need to pass the payment_id instead of the txid

Method: **_GET_**
```
api.minepi.com/v2/payments/{payment_id}
```

**Comment by vidaniello** [comment]
Tanks! now work!
