### ISSUE TITLE
A free miner of population usage

### ISSUE THREAD

**Issue by orhanmutlu1** [pi-apps/pi-platform-docs#79]
People will mine for free but not when they are alone..

**Comment by mohammed1133451** [comment]
Nice to meet you

**Comment by onyirosy** [comment]
Hello, nice to meet you too.

**Comment by onyirosy** [comment]
Hi, I need help sending a video. Each time I tried they tell me video too
large even after reducing it.

**Comment by onyirosy** [comment]
Hi, I need help on how to send a short video about hackathon project.
