### ISSUE TITLE
hello-world

### ISSUE THREAD

**Issue by trantuananhvt** [pi-apps/pi-platform-docs#8]

**Comment by Sten435** [comment]
Why do you open issues without writing a problem?

Don't do that, please.

Its spam.

Thanks

**Comment by trantuananhvt** [comment]
Actualy, i'm not 100% understand what i did. I need to learn moẻ !

**Comment by ali143shahbaz444** [comment]
Great worck😇

**Comment by FAHEEMIQBAL84** [comment]
On Wed, 30 Jun 2021 at 6:07 PM, ali143shahbaz444 ***@***.***>
wrot wo kyse
