### ISSUE TITLE
Camera support!

### ISSUE THREAD

**Issue by Sten435** [pi-apps/pi-platform-docs#80]
The Pi browser is missing camera support! I need it for my hackathon project.

Nicolas told me on the zoom meeting that there is a way but i can't find a way on to use the camera with the Pi browser.

Are you guy's working on this?

Greetings.

**Comment by Liubo88888** [comment]
This is a good proposal!

**Comment by Sten435** [comment]
@aurelienshz do you know somthing about this issue?

**Comment by hklee93** [comment]
Hi, the feature is somewhat ready, but it hasn't been reviewed yet. It might take a while to actually be released, but just to let you know, this feature will be available in the future.
