### ISSUE TITLE
Pi Browser not rendering always (rarely not render, most of times it renders)

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#81]
I openned Pi Browser in my cellphone, enter my app, it loaded, but didn't rendered, and only render when I go to URL bar. (It happens rarely).

https://user-images.githubusercontent.com/5984401/128034056-f708b6e9-24a0-438e-b26e-2f686281b1e5.mp4

It was loaded, but didn't render. It happens rarely, not always. But it didn't happened before. In another cellphone happened the same, always rarely.

If I try again in my cellphone, it works well.

https://user-images.githubusercontent.com/5984401/128034502-5613435f-2ff8-4f99-acf4-742c3cffc641.mp4

I think it's a thing with the cache or the timeout when charging the apps, that don't render on time always. It's known that Pi Browser isn't managing well the cache by this issue:

https://github.com/pi-apps/pi-platform-docs/issues/69

**Comment by hklee93** [comment]
This might have been fixed recently. Please feel free to raise an issue again if it still happens. Thanks!
