### ISSUE TITLE
Permit download files with Pi Browser

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#82]
Add permission in mobile, to use storage to download files with Pi Browser.

**Comment by Sten435** [comment]
Yep, i need this tp for my application to download images (png...)

**Comment by onyirosy** [comment]
Exactly, pls do permit download files with pi browser

**Comment by hklee93** [comment]
As you requested on the discord channel, this is on the TODO list, but might not be released soon. Will let you know how it goes.
