### ISSUE TITLE
Unable to verify phone number

### ISSUE THREAD

**Issue by nickojay** [pi-apps/pi-platform-docs#85]
Sent sms 2day ago and still phone wqsnt even verified multiple tries of manual verification only loads

**Comment by aszasz1234** [comment]
This place isn't for you to ask this question.

**Comment by jhasatishc** [comment]
> Sent sms 2day ago and still phone wqsnt even verified multiple tries of manual verification only loads

Pls check if your phone has international calling facility, phone verification process requires international SMS to be sent from your mobile. In India, from prepaid mobile we top up Rs.10/- to send international SMS or postpaid mobile needs to have international calling facility. Once your phone has international calling facility, SMS will go smoothly and phone verified.

I had similar problem like yours, and it was solved once my mobile had international calling facility.

**Comment by hklee93** [comment]
Irrelevant topic. Closing the issue here.

**Comment by Auaman11** [comment]
Hello Sir , before six months I'm using postpaid that's international call allow
