### ISSUE TITLE
Error when calling the SDK

### ISSUE THREAD

**Issue by Sten435** [pi-apps/pi-platform-docs#9]
When i call Pi.authenticate i get this error:

main.js:8 Error: Pi Network SDK was not initialized. Call init() before any other method.
    at k.<anonymous> (pi-sdk.js:1)
    at pi-sdk.js:1
    at Object.next (pi-sdk.js:1)
    at pi-sdk.js:1
    at new Promise (<anonymous>)
    at Y (pi-sdk.js:1)
    at k.authenticate (pi-sdk.js:1)

**Comment by mitjans** [comment]
Check out this [issue](https://github.com/pi-apps/pi-platform-docs/issues/2#issuecomment-870213077)

**Comment by mitjans** [comment]
Check ou this [issue](https://github.com/pi-apps/pi-platform-docs/issues/6)

**Comment by Sten435** [comment]
Sorry but this does not fix my problem, I already did that.

The error I get is:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided
('https://app-cdn.minepi.com') does not match the recipient window's origin
('http://127.0.0.1:5500').

Op di 29 jun. 2021 om 13:19 schreef Carles Mitjans ***@***.***

**Comment by mitjans** [comment]
That happens because you have to try your webapp inside the Pi Browser to correctly authenticate the user. If you try it in any other browser, it won't work.

It would be awesome if @kokkalis or any other staff member brought some light on how tot test our apps without having to use Pi Browser.

**Comment by Sten435** [comment]
Thanks to clarify that bud.

That really helped me.

👌🏻🤟
