### ISSUE TITLE
When I use the sandbox to test the payment, it returns Error: Request failed with status code 500

### ISSUE THREAD

**Issue by voodooq** [pi-apps/pi-platform-docs#91]
I passed the authorization to start the payment, but instead of popping up the confirmation page, an error was returned on screen:  
Error
An unexpected error occurred.

And I saw an error in the console: Error: Request failed with status code 500

I Use the code
let pi_amount = '3.14';
        const paymentData = {amount: pi_amount,	memo: "Pay pi buy starts",	metadata: { "amount":pi_amount}};
        const callbacks = {
          onReadyForServerApproval: onReadyForServerApproval,
          onReadyForServerCompletion:onReadyForServerCompletion,
          onCancel: onCancel,
          onError: onError
        };
        const payResult = Pi.createPayment (paymentData, callbacks);

I have no idea how to solve this problem
![微信截图_20210903175902](https://user-images.githubusercontent.com/20252405/131987650-08a906b9-93e3-441b-b0ca-285a6ab14bab.png)

**Comment by ronielex** [comment]
Please help to understand thank you.

**Comment by voodooq** [comment]
I fixed this problem, but I got another problem. The screen kept counting down for 60 seconds without any errors, and then it displayed timeout. There is no pop-up page for users to confirm.
![微信图片_20210906121719](https://user-images.githubusercontent.com/20252405/132159966-e4e48ba2-e567-4518-b36d-8e3e9eefd134.jpg)
![微信图片_20210906121726](https://user-images.githubusercontent.com/20252405/132159972-96f0e3ca-e824-4563-89d1-ba2ea5685716.jpg)

**Comment by hklee93** [comment]
When the timer shows, you need to hit Pi's /approve endpoint from your server.

**Comment by hklee93** [comment]
Seems stale. Feel free to open again if you're still having trouble.
