### ISSUE TITLE
my Web app displays differently in Pi Browser on iOS

### ISSUE THREAD

**Issue by culturebets** [pi-apps/pi-platform-docs#94]
Good day, i think this issue is experienced by many (as seen on discord). I made several tests and it sum up to this observation:
My app (piorg.io) displays perfectly fine on Pi Browser but when i test on iOS, it doesn't display properly. On the side note, i tested one of the apps (pitalk.com) in which it displays on iphone 7. but updated iphone models of iOS doesn't.

Iphone IOS Issue ( model: Iphone X )
https://piorg.io/github/iphone_issue.mp4

Android 11 handset Miui 12 (model: Xiaomi X3 Pro)
https://piorg.io/github/android_no_issues.mp4

**Comment by hklee93** [comment]
Is this still an issue? I can't see the videos you uploaded. Feel free to open a new issue if it's still the case. Thanks.
