### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by 13pharaon** [pi-apps/pi-platform-docs#96]
J'ai réinitialisé mon code code de compte pour la changer, mais depuis 4 mois je n'arrive plus à accéder à mon compte et de miner. La vérification au serveur est sans succès. Alors que dans pi browser mon compte est visible mais toujours inaccessible 🙏🙏

**Comment by hklee93** [comment]
Hi, this is not a place for troubleshooting. Please reach out to either Mod within your language chat or reach out to support@minepi.com
